### ISSUE TITLE
`deadpool-sqlite` `ConnectionWrapper` is not `async`-safe

### ISSUE THREAD

**Issue by SergioBenitez** [bikeshedder/deadpool#114]
`ConnectionWrapper` wraps a `rustqlite::Connection` which implements a `Drop` that [may perform synchronous I/O](https://docs.rs/rusqlite/0.25.3/src/rusqlite/lib.rs.html#332-337):

```rust
impl Drop for Connection {
    #[inline]
    fn drop(&mut self) {
        self.flush_prepared_statement_cache();
    }
}
```

Thus, when (the last of the clones of) `ConnectionWrapper` is dropped, synchronous I/O will be performed in what is surely to be an async context. This is, of course, logically incorrect behavior that can lead to quite a few problems including panics.

In general, wrapping a synchronous connection _correctly_ (or any other I/O object) is incredibly error-prone. Please see our implementation in `rocket_sync_db_pools` where we've painstakingly tried to address all of the relevant issues: https://github.com/SergioBenitez/Rocket/blob/693f4f9ee50057fc735e6e7037e6dee5b485ba10/contrib/sync_db_pools/lib/src/connection.rs.

**Comment by bikeshedder** [comment]
Good catch. I didn't think of this.

I did hesitate to add any sync database drivers to `deadpool` for that exact reason. I should've known better than releasing a half-baked implementation of this. :disappointed:

Please review #115 which fixes this problem. Thanks a lot!
