### ISSUE TITLE
can't use rustls in deadpool-lapin

### ISSUE THREAD

**Issue by icryrainix** [bikeshedder/deadpool#118]
Even through I enabled rustls in lapin, but deadpool-lapin still use openssl. How can I use rustls in deadpool-lapin?

**Comment by bikeshedder** [comment]
I see. `lapin` enables the `native-tls` feature by default.

I guess `deadpool-lapin` should depend on `lapin` without default features in the future.

I wonder why it uses `openssl` in your case. This feature is not enabled by default. Could you check the output of `cargo tree --format "{p} {f}"` why this feature is enabled.

**Comment by bikeshedder** [comment]
@icryrainix I haven't heard from you for quite some time now and can only assume that this issue is no longer relevant? Feel free to reopen this issue.
