### ISSUE TITLE
Returning a Pool with or without TLS ?

### ISSUE THREAD

**Issue by Zerowalker** [bikeshedder/deadpool#129]
I am trying to have a function return either a Pool with or without TLS,
and i had it working until there was some changes in 0.8.0 i believe.

Now i just can't seem to make it work, i tried making sense of the source code to work something out to no avail sadly.

pseudo code
```
if config.ssl {
   ....
   let connector_tls = postgres_native_tls::MakeTlsConnector::new(connector)
   db_cfg.create_pool(connector_ts)
 } else{
   db_cfg.create_pool(NoTls)
 }
}
```

**Comment by bikeshedder** [comment]
Can you show the code that used to work and provide the error that you run into?

**Comment by bikeshedder** [comment]
Sorry for the long delay. I  just saw your question there:

> Is type returned by create_pool are the same no matter if it's with TLS or just NoTls, (just a Pool) and returning it from a function as such is what's expected?

Yes. `create_pool` returns a `Result<Pool, ConfigError>`. See https://docs.rs/deadpool-postgres/0.9.0/deadpool_postgres/config/struct.Config.html#method.create_pool

Did you figure it out? If it is not a deadpool related issue feel free to close this.
