### ISSUE TITLE
Usage with Diesel's `load` method

### ISSUE THREAD

**Issue by dchenk** [bikeshedder/deadpool#133]
Hi and thanks for this great crate. I see the example for using deadpool_diesel with the `interact` API, but it seems to be impossible to use the pool with, for example, the Diesel `load` method (same for `get_result`, etc.). I've tried doing a double-deref and a bunch of other things, but I may be misunderstanding how to use this crate. Could you @bikeshedder please show a minimal example of what the value you get out of `pool.get().await.unwrap()` can be used with Diesel's query DSL methods (https://github.com/diesel-rs/diesel/blob/master/diesel/src/query_dsl/mod.rs)?

Thank you in advance.

**Comment by bikeshedder** [comment]
I guess you found the problem: https://github.com/dchenk/deadpool/commit/e19f0cb5ef7027b093f576d52df8e0d9c423774b

I'm more than happy to add this change and make an immediate release.

Are you working on a PR?

**Comment by dchenk** [comment]
I'd be happy to submit a PR with the needed changes to get `deadpool` to work with the upcoming Diesel release, where Diesel will require a mutable reference to a connection. Please note that the change would not be valid for the _current_ Diesel version.

But my question was about something else: I thought I was doing something wrong at first and was not understanding `deadpool`'s API. As far as I can tell now, you deliberately only exposed the `interact` method to help prevent accidental blocking IO on a core tokio thread. (Please correct me if I got _that_ wrong, haha.) 

What I ended up doing is adding a method (which you [noticed here](https://github.com/dchenk/deadpool/commit/084e8e9d1dd036165085c8fdbb800deec12f34db)) to let a consumer of `deadpool` get the internal (Mutex-guarded) connection. I wanted to experiment and see how the API would feel. Overall I'm finding it satisfactory, and I think needing to call `.lock()` on the mutex when a connection is needed is not a big deal.

So this can be two independent PRs:
1. It's probably worth adding an `inner_obj` method that returns an `Arc<Mutex<T>>` as you saw in my fork. (Detailed explanation [here](https://github.com/dchenk/deadpool/commit/084e8e9d1dd036165085c8fdbb800deec12f34db#commitcomment-56756401).)
2. Before the next Diesel version is released, change the `interact` method to give the closure that's passed in a _mutable_ reference to `T`.
