### ISSUE TITLE
Two Broken clippy lints

### ISSUE THREAD

**Issue by dessalines** [bikeshedder/deadpool#168]
I'm getting the following when running clippy on `1.51.0`, which seem to suggest deadpool requires nightly.

```
error[E0710]: an unknown tool name found in scoped lint: `rustdoc::broken_intra_doc_links`
/home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/deadpool-runtime-0.1.2/src/lib.rs:6:5
rustdoc::broken_intra_doc_links,
^^^^^^^
```

```
error[E0658]: arbitrary expressions in key-value attributes are unstable
/home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/deadpool-runtime-0.1.2/src/lib.rs:1:10
#![doc = include_str!("../README.md")]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
608  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
```

**Comment by bikeshedder** [comment]
That `#![doc = include_str!(...)]` feature was added in rust 1.54.0: https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html

A simple `rustup update` should fix it for you.

Maybe using that feature is a bit too bleeding edge?

@tyranron I was worried that people might run into this. I'm tempted to go back to inlining the README.md into the `lib.rs` files and using the sync script until Rust 1.54 is at least 12 months old. Is there maybe a way to check the Rust version and just skip that directive if the rust version does not support it? The documentation won't include the README, then, but using it will work just fine.

**Comment by dessalines** [comment]
> Is there maybe a way to check the Rust version and just skip that directive if the rust version does not support it? The documentation won't include the README, then, but using it will work just fine.

That would be ideal for me. 

Unfortunately I'm currently using https://hub.docker.com/r/ekidd/rust-musl-builder on a CI to build production versions of lemmy, which hasn't had an update since `1.51` :frowning: , but I'm trying to get other docker rust alpine versions working, so I don't have to be locked to that old one. I'll close this if / when I can get those working which would make this a non-issue for me.

**Comment by tyranron** [comment]
@bikeshedder 

> I was worried that people might run into this. I'm tempted to go back to inlining the README.md into the `lib.rs` files and using the sync script until Rust 1.54 is at least 12 months old.

Yup, there is definitely some risk. But let's not be too harsh on this. This is the first issue with this, and as @dessalines has described, it comes not from the project requirements, but rather from using some outdated non-well-maintained tooling.

Let's try first to help @dessalines resolve the tooling problem and postpone this. Let's consider codebase/MSRV chages only if we will run into this issue once again. I have a feeling that it shouldn't be a wide-spread case for library users.

> Is there maybe a way to check the Rust version and just skip that directive if the rust version does not support it? The documentation won't include the README, then, but using it will work just fine.

Yup, this should be possible if we'd poke with [`rustversion` crate](https://crates.io/crates/rustversion) or similar.

-----------------------------------

@dessalines regarding your situation, would you be so kind to shed more light on it?

You want to build a binary or a Docker image? Is using `alpine` is a hard requirement (I guess so, if you need statically linked binary outside Docker image)? Or if you need a Docker image and your aim is to have it as slim as possible, would distroless, but build-on-Debian will satisfy you?

**Comment by dessalines** [comment]
Okay I finally found a new musl image that works! 

Switched from `ekidd/rust-musl-builder:1.51.0` to `clux/muslrust:1.56.0`

I'll close this, as that resolved it. Unless other people are stuck on old rust versions, this is probably a non-issue.
