### ISSUE TITLE
Provide a `deadpool_postgres::Client` type alias

### ISSUE THREAD

**Issue by jbg** [bikeshedder/deadpool#17]
Thanks so much for this crate!

`deadpool_lapin` has this handy type alias:

```rust
pub type Connection = deadpool::Object<lapin::Connection, Error>;
```

… but `deadpool_postgres` is missing an equivalent (I guess it would be `deadpool_postgres::Client`).

It would be useful because it means a crate using `deadpool_postgres` doesn't need to also depend on `deadpool` just to get the type, if it wants to pass around a database client that it got from the pool.

**Comment by jbg** [comment]
Had a look at making a PR, but I note that there's an existing `Client` type in `deadpool_postgres`, which raises a naming and backwards-compatibility issue.

`Client` seems the obvious name for the type alias, since the alias would be more useful than the struct that's there now (which it would deref to anyway), but naming it that and renaming the struct would be a breaking change.

**Comment by bikeshedder** [comment]
That's indeed an oversight. One should be able to use `deadpool-*` without needing to require `deadpool`. I made the same mistake in `deadpool-redis` which just got fixed, too.

I'm currently working on #9 which changes the API of `Manager` yet another time. So a new minor version is required anyways. I plan to release `0.4` soon.

**Comment by jbg** [comment]
👍 Thanks again!
