### ISSUE TITLE
Feature request: deadpool_redis support redis cluster

### ISSUE THREAD

**Issue by clia** [bikeshedder/deadpool#175]
Wish deadpool_redis support redis cluster mode!
like mobc's support: https://crates.io/crates/mobc-redis-cluster

**Comment by neogenie** [comment]
+1

**Comment by clia** [comment]
Lately I found a solution to use a proxy server between Redis cluster and deadpool driver:
https://github.com/clia/rcproxy

**Comment by bikeshedder** [comment]
Adding support for redis-cluster should be as simple as using `redis-cluster-async` instead of the `redis` crate.

PRs welcome. :+1:
