### ISSUE TITLE
Could we replace Mutex with RwLock?

### ISSUE THREAD

**Issue by NateLing** [bikeshedder/deadpool#182]
This is rust-lang doc.

[RwLock](https://doc.rust-lang.org/std/sync/struct.RwLock.html)

> This type of lock allows a number of readers or at most one writer at any point in time. The write portion of this lock typically allows modification of the underlying data (exclusive access) and the read portion of this lock typically allows for read-only access (shared access).
> 
> In comparison, a [Mutex](https://doc.rust-lang.org/std/sync/struct.Mutex.html) does not distinguish between readers or writers that acquire the lock, therefore blocking any threads waiting for the lock to become available. An RwLock will allow any number of readers to acquire the lock as long as a writer is not holding the lock.

**Comment by tyranron** [comment]
@NateLing it depends on the concrete code piece and its workload. Can you point to the concrete piece of code where you think it should be replaced?

**Comment by NateLing** [comment]
@tyranron  i saw the [PR](https://github.com/bikeshedder/deadpool/pull/180/files). in `src/managed/mod.rs`.  Maybe we could replace it.

**Comment by tyranron** [comment]
@NateLing in the `src/managed/mod.rs` file `Mutex` is used to guard `PoolInner::slots`.  The way this field is used is mainly mutation of it: [1](https://github.com/bikeshedder/deadpool/blob/deadpool-v0.9.2/src/managed/mod.rs#L360), [2](https://github.com/bikeshedder/deadpool/blob/deadpool-v0.9.2/src/managed/mod.rs#L440), [3](https://github.com/bikeshedder/deadpool/blob/deadpool-v0.9.2/src/managed/mod.rs#L465-L492), [4](https://github.com/bikeshedder/deadpool/blob/deadpool-v0.9.2/src/managed/mod.rs#L571-L580). Using `RwLock` instead will give no benefit in this situation, only complicating the contention for writing/mutation (being the main scenario here). So, on my opinion, the `Mutex` is used here correctly.

Consider the following info regarding `Mutex` vs `RwLock`:
- https://stackoverflow.com/a/68947308/1828012
- https://fy.blackhats.net.au/blog/html/2018/10/19/rust_rwlock_and_mutex_performance_oddities.html
- https://www.reddit.com/r/rust/comments/f4zldz/i_audited_3_different_implementation_of_async/

**Comment by bikeshedder** [comment]
The lock is never acquired for reading purposes. `RwLock` is slightly slower when just using `RwLock::write()` so it would indeed decrease the performance slightly if it was used instead of the `Mutex`.

In a previous version of `deadpool` I used a `crossbeam` queue instead of a `Mutex<Vec<...>>` but implementing a correct resizable pool that way is rather difficult. Also `crossbeam` is not necessarily faster and in highly contested workloads can sometimes even be slower than just using a plain old mutex.

**Comment by bikeshedder** [comment]
Closing this as `RwLock` has no benefit over `Mutex` the way it is used inside of `deadpool`.
