### ISSUE TITLE
impl std::error::Error for PoolError, RecycleError

### ISSUE THREAD

**Issue by walfie** [bikeshedder/deadpool#19]
This would make it more convenient to use with `?`.

The impl could be limited to cases where the backend error is compatible, i.e., `where E: std::error::Error`.

**Comment by bikeshedder** [comment]
Could you please give this a try? If everything is fine I'll publish Version 0.4.3 to crates.io

**Comment by walfie** [comment]
Works for me! Thanks for the quick response.

I feel like usually `fmt::Display` impls for errors tend to have a human-readable description like "backend error while recycling connection: {}" rather than a debug-like message such as "RecycleError::Backend {}", however this is more of a style/preference thing and is subjective.

**Comment by walfie** [comment]
it may also be useful to define `source()` to return `Some` in the case of a backend error, although it would then also require E to be `'static`, and I'm not entirely sure what the best practices are regarding that. (I personally don't need it, however)

**Comment by bikeshedder** [comment]
I changed the error messages to something human readable and published `v0.4.3`.

https://crates.io/crates/deadpool/0.4.3

Thanks a lot for the feedback.

**Comment by walfie** [comment]
Thanks!
