### ISSUE TITLE
Don't use the --workspace flag for running CI tasks

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#190]
This is a blocker for #189 to be merged.

**Comment by elpiel** [comment]
I guess the CI workflow should run the checks for each crate separately then?

**Comment by bikeshedder** [comment]
@elpiel yes. If you want to work on it a PR would be highly appreciated. :+1: 

I'm not very familiar with the GitLab CI pipeline configuration. @tyranron has done the most work on the project configuration.
