### ISSUE TITLE
Could update diesel to 1.4.8?

### ISSUE THREAD

**Issue by NateLing** [bikeshedder/deadpool#193]

**Comment by bikeshedder** [comment]
`deadpool-diesel` depends on `diesel 1.4.3` but that only defines the minimum version requirement. If you run `cargo update` in your own project you will get the latest `diesel` version and as long as `diesel` doesn't break semantic versioning it should be fully compatible.

**Comment by NateLing** [comment]
aha, sorry.

**Comment by bikeshedder** [comment]
fyi. The `diesel 1.4.3` requirement means that any `diesel` version `>= 1.4.3` and `< 2` is considered compatible. I should've been more clear about that. `diesel 2.0` would be considered non-compatible following the semantic versioning rules: 

> (...) Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

See: https://doc.rust-lang.org/cargo/reference/semver.html
