### ISSUE TITLE
Split status.available in two values

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#199]
It's confusing that `Status.available` can reach negative values as seen in #191. Therefore the `Status` struct should probably be changed to this structure:

```rs
/// The current pool status.
#[derive(Clone, Copy, Debug)]
pub struct Status {
    /// The maximum size of the pool.
    pub max_size: usize,

    /// The current size of the pool.
    pub size: usize,

    /// The number of available objects in the pool.
    pub available: size,

    /// The number of futures waiting for an object.
    pub waiting: size,
}
```

**Comment by dtamai** [comment]
A few days ago I was running some simulations using this crate and I needed the number of users waiting for a resource and, since the Status struct doesn't have it right now, I implemented it in the simulation side.
Later I found this issue, so I opened the PR #202 that implements the split you proposed.

**Comment by bikeshedder** [comment]
As you probably noticed I already prepared this change by replacing the `available: AtomicIsize` by an `users: AtomicUsize`. That change is not part of any published version of the crate and I want to support the old `Status` structure for at least one more release. I'm planning a rather major rework of the internals so I'm saving the major update for that.

Also I wonder if it's really necessary to implement that `users > size` logic in the `status` method. If `users` exceeds `size` it's pretty obvious what this means. In my initial post I wrote that I'm planning to have two fields here, but now that the code uses a `users` field internally I wonder if the following struct doesn't work just as well:

```rs
/// The current pool status.
#[derive(Clone, Copy, Debug)]
pub struct Status {
    /// The maximum size of the pool.
    pub max_size: usize,

    /// The current size of the pool.
    pub size: usize,

    /// The number of users of the pool. This number may exceed
    /// the pool size meaning that there are workers waiting.
    pub users: size,
}
```

I haven't touched the `unmanaged` pool for quite some time. I was planning to update this code when I'm ready to release a new major version of this crate.

fyi. This is the milestone tracking this: https://github.com/bikeshedder/deadpool/milestone/4

**Comment by dtamai** [comment]
> If users exceeds size it's pretty obvious what this means. In my initial post I wrote that I'm planning to have two fields here...

I agree! It does seem that having `available` and `waiting` is unnecessary because at any moment one them is zero, and both of them can be inferred from `users` and `size`. At least in my simulations I would only use the `waiting` count.

**Comment by LukeMathWalker** [comment]
As a user of the crate, even though it's possible to infer who is waiting from the `users` field, I'd prefer to have `available`/`waiting` as interface. I find it clearer and it doesn't lead me to make potentially incorrect assumptions (e.g. that users will always be smaller than available).

Having `users` be potentially bigger than `available` doesn't feel like a significant improvement over `available` being potentially negative to indicate contention.
