### ISSUE TITLE
Queries against a schema are send to another

### ISSUE THREAD

**Issue by mamcx** [bikeshedder/deadpool#204]
After I move to async, I get sometimes the behavior of certain data sent to another schema, and that is terrible because this is for a multi-tenant setup.

I run all inside actix, and execute in each request:

```sql
SET search_path = NAME_SCHEMA, public, pg_catalog
```

This works most of the time but is unclear to me how or when this fails. It could have been related to the error "current transaction is aborted, commands ignored until end of transaction block" but I'm unsure.

I wonder if this could be related to the use of connection pools:

```rust
    #[tracing::instrument(name = "PG OPEN")]
    pub async fn open(conn: PgCon) -> Result<Self, Error> {
        //dbg!(&conn);

        let conn2 = conn.clone();
        let mut cfg = Config::new();
        cfg.dbname = Some(conn.db);
        cfg.user = Some(conn.user);
        cfg.host = Some(conn.host);
        cfg.password = conn.pwd;
        cfg.port = Some(conn.port);
        cfg.application_name = conn.app;

        cfg.manager = Some(ManagerConfig {
            recycling_method: RecyclingMethod::Fast,
        });

        let pool = cfg.create_pool(Some(Runtime::Tokio1), NoTls)?;

        Ok(Self { pool, conn: conn2 })
    }
```

So:

How to be certain the schema scoping is valid in each request?

**Comment by bikeshedder** [comment]
This could have to do with the way `tokio-postgres` is implemented and how connection pooling works in general. If you start a query and drop the future the query will still be executed. Returning the connection to the pool doesn't stop it processing already queued queries. Another task could end up receiving the same connection and executing some other queries concurrently causing mangled state if you execute commands like `SET`. If I'm not mistaken `SET` does apply to the whole connection if not executed inside a transaction. 

The `RecyclingMethod::Fast` is usually a safe bet, but in your case you might be better of issuing at least a `CLOSE ALL` which makes sure that all cursors are closed: https://www.postgresql.org/docs/current/sql-close.html

Alternatively `RecyclingMethod::Clean` does that and also issues some additional queries making sure that the connection is in a pristine state: https://docs.rs/deadpool-postgres/latest/deadpool_postgres/enum.RecyclingMethod.html

That's currently the only way I can explain this behavior.

When you abort a HTTP request to your actix server the handler is not polled to completion and the code will stop executing at the very next `.await` inside the handler of functions called by it. That's a lesson I learned the hard way when implementing the first versions of deadpool two years ago. I highly recommend testing your code against clients that send HTTP requests and close the connection prematurely. It's a special kind of fuzzing specific to the way async-await is implemented in Rust.

**Comment by mamcx** [comment]
Ok, I set `RecyclingMethod::Clean` but then the SET get cleared in the same execution path. I run:

```rust
pub async fn set_schema(self, schema: &str) -> Result<Self, Error> {
         let mut db = self;
        let cmd = format!("SET search_path = {} , public, pg_catalog", schema);
        db.exe_sql(&cmd).await?;
        db.conn.schema = Some(schema.into());

       Ok(db)
}

pub async fn check_db_version() -> Result<i32, CoreErr> {
   let con = Pg::open(..) //the same of above with RecyclingMethod::Clean

    let con =  con.set_schema(company).await;

    let db_version =  con
            .select_one::<i32>("SELECT db_version()", ().into())
            .await?; <--- ERROR HERE

        Ok(v.unwrap_or_default())
}
```

and the last query is without the correct `search_path`. This makes sense because in async the connection does not necessarily return the same `connection` in each `await`, but then, in this case, I must stop using a pool?

**Comment by bikeshedder** [comment]
The pool will give you the first available connection object. You must not return an object hoping for the pool to give you back the same object at a later point. If that is indeed how you tried to solve it you need to change your strategy.

If you really want to not worry about the `search_path` being set correctly everywhere you could add a `pre_recycle` and `post_create` hook that does execute the `SET search_path` using the tenant stored in a [LocalKey](https://docs.rs/tokio/latest/tokio/task/struct.LocalKey.html). Once you've done that you only need to update the `LocalKey` for every request.

**Comment by bikeshedder** [comment]
Just to be sure. Your `con.exe_sql` and `con_select_one` do call `self.pool.get().await` under the hood and drop the client object afterwards? That would indeed explain the behavior you're describing.

**Comment by mamcx** [comment]
Yes, I do that (following examples).  But then If I need to store the result the pool will be discarded.

**Comment by bikeshedder** [comment]
You should create the pool once at the application startup and register it in `actix-web` as `app_data`. There is an example in the repository how to use `deadpool-postgres` with `actix-web`: https://github.com/bikeshedder/deadpool/blob/master/examples/postgres-actix-web/

If you want to issue the `SET` query every time an object is created or recycled you can utilize hooks:
- https://docs.rs/deadpool/latest/deadpool/managed/struct.PoolBuilder.html#method.post_create
- https://docs.rs/deadpool/latest/deadpool/managed/struct.PoolBuilder.html#method.post_recycle

The `post_create` hook is called when the pool is currently empty and a new object has been created and `post_recycle` is called after recycling an object.

Alternatively you could write your own wrapper that ensures that the `search_path` is always set. It seams you're trying to do exactly that. Just don't get a client object from the pool, set the search_path and drop it right afterwards. You need to hold onto that object for this to work. Otherwise you always end up with a new client that might not have the correct search_path set.

**Comment by mamcx** [comment]
Excellent, this is the way. I change my code to always set things in the `pool.get()`.
