### ISSUE TITLE
All CI actions are skipped for PRs

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#210]
@elpiel Since merging #207 all CI actions are skipped for new PRs. That's rather unfortunate. :-/

@tyranron Any ideas what could be causing this? I thought it was just a glitch of PR #207 but now that it's merged it seams to affect future PRs as well.

**Comment by bikeshedder** [comment]
Example #209

**Comment by elpiel** [comment]
It's the if-statement that we removed `!contains(github.event.head_commit.message, '[skip ci]')` now any commit message will skip the CI.

I guess the if statements are for: don't run CI job if we are on `master`  or tag starting with `deadpool-`

**Comment by elpiel** [comment]
Removing the if-statement should be enough since the `[skip ci]` is handled automatically by GH actions then the `on` config is sufficient.
