### ISSUE TITLE
deadpool-sqlite transactions?

### ISSUE THREAD

**Issue by rongcuid** [bikeshedder/deadpool#215]
Is there a way to get a transaction object out of Rusqlite? Currently the entire transaction can only be performed synchronously.

For reference, `sqlx` can perform transactions asynchronously.

**Comment by bikeshedder** [comment]
`rusqlite` uses the `libsqlite3` C library internally and while the C library code seams to have some [async capabilities](https://www.sqlite.org/asyncvfs.html) none of those are useable via `rusqlite` right now: 

- https://github.com/rusqlite/rusqlite/issues/1075

That's the reason why `deadpool-sqlite` uses `deadpool_sync::SyncWrapper` which ensures that you're not using it directly without wrapping the calls inside `spawn_blocking`.

I don't know how sqlx does it, but I can only guess that they either make use of the async features of the C library or fake the async behavior by spawning a thread and passing queries and results back and forth via channels.

**Comment by rongcuid** [comment]
I investigated `sqlx`'s implementation. It actually has worker threads to do the execution. `sqlx` doesn't actually have connection pooling for SQLite, and each connection comes with its own worker thread.

**Comment by bikeshedder** [comment]
So what's your thoughts on that? The `deadpool-sqlite` crate could provide a convenience wrapper that uses worker threads and some channels to take care of the communication.

Right now you can use the `interact` method which makes use of the thread pool provided by your async runtime. It's not as pretty as directly calling methods but at least it's very explicit and you're well aware that sqlite in fact isn't an async DB driver.

I do understand that the added verbosity is rather annoying though so maybe some convenience functions to the wrapper objects could help that hide the `interact` calls somehow?

**Comment by bikeshedder** [comment]
If you want to work on an async wrapper for SQLite feel free to open a PR. :+1: 

I'm closing this for the time being.
