### ISSUE TITLE
replacing the ``async_trait``  to  ```BoxFuture```

### ISSUE THREAD

**Issue by zhuxiujia** [bikeshedder/deadpool#218]
If v1.0 has break changes, I recommend replacing the ``async_trait``  to  ```BoxFuture```?

1. there are usually only impl  trait and two function to implement to Deadpool.I do not want to introduce Async_traits to increase system compilation time.
2. the crate `async_trait` how to work?   It looks like it's going to generate a lot of variables that you don't know。  see this code
```rust
// Input:
//     async fn f<T>(&self, x: &T, (a, b): (A, B)) -> Ret {
//         self + x + a + b
//     }
//
// Output:
//     Box::pin(async move {
//         let ___ret: Ret = {
//             let __self = self;
//             let x = x;
//             let (a, b) = __arg1;
//
//             __self + x + a + b
//         };
//
//         ___ret
//     })
```
3.  rust 2022 will impl the  async trait , maybe we need wait it complete see [async-fn](https://rust-lang.github.io/rfcs/3185-static-async-fn-in-trait.html)

This will reduce the uncertainty introduced by the Async_trait procedure macro.
I think this change will be simple enough。
the code just like  this
```rust
use std::future::Future;
use std::pin::Pin;
pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;
use deadpool::managed::RecycleResult;
pub trait Manager: Sync + Send {
    /// Type of [`Object`]s that this [`Manager`] creates and recycles.
    type Type;
    /// Error that this [`Manager`] can return when creating and/or recycling
    /// [`Object`]s.
    type Error;

    /// Creates a new instance of [`Manager::Type`].
    fn create(&self) -> BoxFuture<'_,Result<Self::Type, Self::Error>>;

    /// Tries to recycle an instance of [`Manager::Type`].
    ///
    /// # Errors
    ///
    /// Returns [`Manager::Error`] if the instance couldn't be recycled.
    fn recycle(&self, obj: &mut Self::Type) -> BoxFuture<'_,RecycleResult<Self::Error>>;

    /// Detaches an instance of [`Manager::Type`] from this [`Manager`].
    ///
    /// This method is called when using the [`Object::take()`] method for
    /// removing an [`Object`] from a [`Pool`]. If the [`Manager`] doesn't hold
    /// any references to the handed out [`Object`]s then the default
    /// implementation can be used which does nothing.
    fn detach(&self, _obj: &mut Self::Type) {}
}

pub struct MyManager{}
impl Manager for MyManager{
    type Type = ();
    type Error = ();

    fn create(&self) -> BoxFuture<'_, Result<Self::Type, Self::Error>> {
        Box::pin(async move{
            todo!()
        })
    }

    fn recycle(&self, obj: &mut Self::Type) -> BoxFuture<'_, RecycleResult<Self::Error>> {
        Box::pin(async move{
            todo!()
        })
    }
}
```

**Comment by bikeshedder** [comment]
I do want to release a [`0.10`](https://github.com/bikeshedder/deadpool/milestone/4) that includes most (if not all) of the breaking changes anyways. I just marked this issue as part of 0.10.

**Comment by LouisGariepy** [comment]
Since GATs landed, there's been some momentum to push the "async in traits" feature. IMO, `deadpool-postgres` should keep using `async_trait` until that feature is stabilized.

For one, it doesn't have any significant impact on compile times (its a small crate with no dependencies, except syn and company which you almost assuredly already have in your dependency graph), and its widely used and battle-tested. It has rough edges, but for the most part, "it just works".

In that sense, I think there's little benefit to introduce this breaking change now, only to break it again in the near-future.

**Comment by bikeshedder** [comment]
Agreed. We can revisit this once "async in traits" feature has landed.
