### ISSUE TITLE
What Rust Type should I use for postgres's timestamp?

### ISSUE THREAD

**Issue by javasn** [bikeshedder/deadpool#23]
What Rust Type should I use for postgres's timestamp?
let a: Timestamp<i64> = row.get("time_edited");
panick happen:
panicked at 'error retrieving column time_edited: error deserializing column 2: cannot convert between the Rust type `postgres_types::special::Timestamp<i64>` and the Postgres type `timestamp`'

**Comment by bikeshedder** [comment]
This is actually a topic for `tokio-postgres`. You can use the `chrono` crate which is supported by `tokio-postgres` (https://docs.rs/tokio-postgres/0.5.1/tokio_postgres/types/trait.FromSql.html) by activating the `with-chrono-0_4` feature. (See: https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/Cargo.toml#L31)

Add this to your `crates.toml` dependencies or update the `tokio-postgres` dependency:

```toml
[dependencies]
tokio-postgres = { version="0.5.1", features=["with-chrono-0_4"] }
```

And then use it:

```rust
let a: chrono::DateTime<chrono::offset::Utc> = row.get("time_edited");
```

**Comment by javasn** [comment]
OK, It works now!
Thank you very much for helping and sharing.

**Comment by bikeshedder** [comment]
You're welcome. 👍
