### ISSUE TITLE
`deadpool_postgres::ClientWrapper` `prepare_cached` and `prepared_typed_cached` documentation typo.

### ISSUE THREAD

**Issue by LouisGariepy** [bikeshedder/deadpool#232]
The `ClientWrapper` documentation for these functions link to the `tokio_postgres::Transaction` page

> Like tokio_postgres::**Transaction**...

But I feel like this should be "Like tokio_postgres::**Client**...", i.e. "Transaction" should be Client here.

I'm ready to submit a PR if this is indeed the case.

**Comment by bikeshedder** [comment]
Thanks a lot. I just fixed it directly. :)
