### ISSUE TITLE
deadpool-bolt::Manager does not derive Debug

### ISSUE THREAD

**Issue by xfbs** [bikeshedder/deadpool#242]
`deadpool_bolt::Manager` does not derive Debug. It would be nice if it did.

**Comment by bikeshedder** [comment]
`deadpool-bolt` is developed and maintained by the `bolt-rs` team.

Please raise this issue in their issue tracker:
https://github.com/0xSiO/bolt-rs/issues

**Comment by bikeshedder** [comment]
Sorry for the late response. I completely overlooked that issue until now. :see_no_evil:
