### ISSUE TITLE
deadpool_postgres::PoolError code: 10022

### ISSUE THREAD

**Issue by Cloud33** [bikeshedder/deadpool#243]
OS: Windows 10
Ver: `deadpool-postgres = "0.10.5"`
Error Details:
```
Backend(Error { kind: Connect, cause: Some(Os { code: 10022, kind: InvalidInput, message: "An invalid parameter was provided." }) })
```
This is a random occurrence, and I cannot stably reproduce it, as if it was due to a socket error?
Does anyone know why?

**Comment by bikeshedder** [comment]
This is an error directly from `tokio-postgres`. Have you checked the PostgreSQL server logs for some errors there?

**Comment by Cloud33** [comment]
I think it's possible that the `postgres sql` connection is running out because I used a relatively large concurrency, `Pool.max_ Size` = 2000, while the `postgres sql` connection default to 100, but investigation is needed. I will try it again at a suitable opportunity and close it first
