### ISSUE TITLE
Update rusqlite to 0.29.0

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#246]
Hello, [0.29.0](https://github.com/rusqlite/rusqlite/releases/tag/v0.29.0) was released recently. Any plans to update?

_Originally posted by @Sparkenstein in https://github.com/bikeshedder/deadpool/issues/162#issuecomment-1510294113_

**Comment by jcramb** [comment]
Just ran into this issue as well - would be nice to see rusqlite version bumped!

**Comment by bikeshedder** [comment]
Fixed in the upcoming release:

- https://github.com/bikeshedder/deadpool/pull/247

**Comment by bikeshedder** [comment]
I meant to give you a heads up. :see_no_evil: 

[deadpool-sqlite 0.6.0](https://crates.io/crates/deadpool-sqlite/0.6.0) was released 6 days ago. :tada:
