### ISSUE TITLE
Documentation: managed defaults

### ISSUE THREAD

**Issue by JosiahParry** [bikeshedder/deadpool#254]
For the managed pool i suspect there are defaults hence the name "managed." However it is unclear what those are and how to find them. 

It would be very helpful if in the managed module documentation the default are documented. For example "there is no max_size or timeout set" would be sufficient if that's true.

**Comment by bikeshedder** [comment]
This is documented in the [`default`](https://docs.rs/deadpool/latest/deadpool/managed) method.

![image](https://github.com/bikeshedder/deadpool/assets/1112569/f454ab0b-623c-4faa-9c99-5b3b5246a597)

Arguably the visibility of this was bad so I also added it to the documentation of the struct fields.

**Comment by JosiahParry** [comment]
Lovely! thank you :)
