### ISSUE TITLE
Include tokio-postgres version in release notes

### ISSUE THREAD

**Issue by christopinka** [bikeshedder/deadpool#257]
It'd be nice to have the tokio-postgres version in release notes. To be able to easily find it for those using tokio-postgres. To satisfy the requirement here - https://github.com/bikeshedder/deadpool/blob/5e6d5927d14583a4d81cc6e0619fb61ef4e8a39d/postgres/README.md?plain=1#L159. Thanks

"Important: The version numbers of deadpool-postgres and tokio-postgres do not necessarily match. If they do it is just a coincidence that both crates have the same MAJOR and MINOR version number."

**Comment by bikeshedder** [comment]
Normally I do mention every time I bump the version of `tokio-postgres` in the `CHANGELOG`: https://github.com/bikeshedder/deadpool/blob/master/postgres/CHANGELOG.md#v081. I just missed that in the `0.8` release which did upgrade to `tokio-postgres 0.7`.

Maybe a table in the `README` would help which shows the mapping of the versions of those two crates?

Something like...

- deadpool-postgres 0.7 – 0.10 -> tokio-postgres 0.7
- deadpool-postgres 0.6 -> tokio-postgres 0.6
- deadpool-postgres 0.4 – 0.5 -> tokio-postgres 0.5
- ...

You can always check the version of the dependency by looking at the `dependency` tab at crates.io: https://crates.io/crates/deadpool-postgres/0.10.5/dependencies

**Comment by christopinka** [comment]
Yes. That all sounds good. Thanks. Your discretion. I'm good with changelog and crates.io.
