### ISSUE TITLE
parsing libpq-style connection strings when using deadpool-postgres

### ISSUE THREAD

**Issue by amitu** [bikeshedder/deadpool#261]
`tokio_postgres::Config` supports ["libpq-style connection strings"](https://docs.rs/tokio-postgres/latest/tokio_postgres/config/struct.Config.html#url), which is not available when using `deadpool-postgres`. 

I think if we add a  `libpq_style_connection_string: Option<String>` to  `tokio_postgres::Config`, and modify `deadpol_postgres::Config::get_pg_config()` to use [`tokio_postgres::Config::from_str()`](https://docs.rs/tokio-postgres/latest/tokio_postgres/config/struct.Config.html#method.from_str), we can support them.

**Comment by amitu** [comment]
Context: Heroku for examples gives us access to DATABASE_URL environment variable, which when we use this crate we have to parse using some other crate first.

**Comment by amitu** [comment]
I have a branch that I am trying this on: https://github.com/bikeshedder/deadpool/compare/master...amitu:deadpool:libpq_style_connection_string

It lacks docs, and ideally it should work with the `Example (from environment)`, which I have not tested yet. 

Not sure about the field I have added, `libpq_style_connection_string`, maybe `connection_string` is better?

**Comment by amitu** [comment]
Hehe, I am sure if someone can bikeshed it's you 😛.

**Comment by edulix** [comment]
This would be a very nice feature :)

**Comment by bikeshedder** [comment]
After some consideration I think `url` and the other parameters could just be additive. That's also possible with the `tokio-postgres::Config` where you first create the `Config` from an URL and then specify the other parameters.

I'll just add a `url: String` property to the `deadpool-postgres::Config` and do exactly that.

**Comment by bikeshedder** [comment]
I just released deadpool-postgres 0.12 to crates.io which does support configuration by URL:

- https://crates.io/crates/deadpool-postgres/0.12.0

You can specify both URL and the other connection parameters and they're merged in order. First the URL is parsed (if it exists) and then the other parameters are applied. Just a note of warning. host and hosts unlike the other parameters are additive.

Initially I thought this being a bad idea but I feel like being able to override things like SSL mode outside of the URL could provide useful in some scenarios. So limiting the user to either URL or structured configuration could be considered an anti feature.
