### ISSUE TITLE
Unresolved imports while adding `0.10.5` version into `Cargo.toml`

### ISSUE THREAD

**Issue by YellingOilbird** [bikeshedder/deadpool#264]
`deadpool-postgres = "0.10.5"`
```
   |
54 | pub use deadpool::managed::reexports::*;
   |                            ^^^^^^^^^ could not find `reexports` in `managed`
```

and after many others `deadpool::managed` imports could not be finded, example:
```
error[E0432]: unresolved imports `crate::CreatePoolError`, `crate::PoolBuilder`, `crate::Runtime`
```

with 0.9.x versions all works fine

**Comment by bikeshedder** [comment]
That's pretty weird. Could you please share your `Cargo.toml`?

**Comment by bikeshedder** [comment]
I'm closing this as `unable to reproduce` for the time being.

**Comment by bikeshedder** [comment]
I'm happy to have a look into this if you share your `Cargo.toml` or even better provide a complete example.
