### ISSUE TITLE
Fix MSRV and Clippy checks in CI pipeline

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#270]
The CI pipeline currently fails because clippy doesn't respect the `rust-version` in the `Cargo.toml` and the MSRV checks fail for some other strange reasons.

**Comment by bikeshedder** [comment]
@tyranron It'd be awesome if you could have a look. I'm currently stuck why that's happening. Especially the Clippy one is annoying as I've added a `rust-version` to the Cargo.toml. I also tried adding a `clippy.toml` which didn't work either.

**Comment by tyranron** [comment]
@bikeshedder I'll look into that today.

**Comment by bikeshedder** [comment]
I think it is safe to increase the MSRV to 1.56 or even 1.59 for all crates.

Just as a reference: The current `tokio` release specifies `1.63` as MSRV.
