### ISSUE TITLE
deadpool-postgres: SslMode does not support `verify-ca` and `verify-full`?

### ISSUE THREAD

**Issue by amitu** [bikeshedder/deadpool#277]
As per PostgreSQL, the `sslmode` should be [verify-ca or verify-full to get MITM protection](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS).  [`deadpool_postgres::SslMode`](https://docs.rs/deadpool-postgres/0.11.0/deadpool_postgres/enum.SslMode.html) only has `prefer` and `require`.

Are there plans to add the `verify-full` etc? Or I am reading this wrong altogether?

**Comment by bikeshedder** [comment]
This is an issue of the underlying `tokio-postgres` crate. `deadpool-postgres` merely mirrors the structures of `tokio-postgres` and adds support for (de)serialization via serde:
- sfackler/rust-postgres#768

**Comment by bikeshedder** [comment]
I'm closing this for the time being as it is blocked by sfackler/rust-postgres#768.
