### ISSUE TITLE
Invalid connection not Drop

### ISSUE THREAD

**Issue by zhuxiujia** [bikeshedder/deadpool#283]
see code
```rust
#[cfg(test)]
mod test {
    use std::sync::Mutex;
    use std::thread::sleep;
    use std::time::Duration;
    use async_trait::async_trait;
    use deadpool::managed::{Manager, Metrics, Object, RecycleError, RecycleResult};
    use once_cell::sync::Lazy;

    struct MockConn {
        pub id: i64,
    }

    pub static Drops: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| {
        Mutex::new(vec![])
    });

    impl Drop for MockConn {
        fn drop(&mut self) {
            println!("mock drop={}", self.id);
            Drops.lock().unwrap().push(self.id);
        }
    }

    struct MockPool {}

    #[async_trait]
    impl Manager for MockPool {
        type Type = MockConn;
        type Error = ();

        async fn create(&self) -> Result<Self::Type, Self::Error> {
            Ok(MockConn { id: 0 })
        }

        async fn recycle(&self, obj: &mut Self::Type, metrics: &Metrics) -> RecycleResult<Self::Error> {
            return Err(RecycleError::Message(format!(
                "Connection is ping fail={}",
                ""
            )));
        }
    }

    #[tokio::test]
    async  fn test_pool() {
        let p = deadpool::managed::Pool::builder(MockPool {}).build().unwrap();
        let mut num = 0;
        for _ in 0..10 {
            let r: Object<MockPool> = p.get().await.unwrap();
            num += 1;
        }
        println!("num={}",num);
        sleep(Duration::from_secs(3));
        assert_eq!(Drops.lock().unwrap().len(), num);
    }
}

```

```log 
mock drop=0
mock drop=0
mock drop=0
mock drop=0
mock drop=0
mock drop=0
mock drop=0
mock drop=0
mock drop=0
num=10
thread 'pool::pool::test::test_pool' panicked at rbdc/src/pool/pool.rs:356:9:
assertion `left == right` failed
  left: 9
 right: 10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aa1a71e9e90f6eb3aed8cf79fc80bea304c17ecb/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/aa1a71e9e90f6eb3aed8cf79fc80bea304c17ecb/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/aa1a71e9e90f6eb3aed8cf79fc80bea304c17ecb/library/core/src/panicking.rs:279:5
   4: rbdc::pool::pool::test::test_pool::{{closure}}
             at ./src/pool/pool.rs:356:9
thread 'pool::pool::test::test_pool' panicked at library/core/src/panicking.rs:144:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/Users/zxj/CLionProjects/rbatis/target/debug/deps/rbdc-ed03f1c26c4d6284 'pool::pool::test::test_pool' --format=json --exact -Z unstable-options --show-output` (signal: 6, SIGABRT: process abort signal)
error: 1 target failed:
    `--lib`
```

**Comment by bikeshedder** [comment]
That's to be expected. It's explained in the `README.md`:
> - **Deadpool is compatible with any executor.** Objects are returned to the pool using the Drop trait. The health of those objects is checked upon next retrieval and not when they are returned. Deadpool never performs any actions in the background. This is the reason why deadpool does not need to spawn futures and does not rely on a background thread or task of any type.

Whenever a object is dropped it is returned "as is" to the pool. Only upon the next `Pool::get` call is the health of the object checked. The pool itself never performs any background tasks.

For applications that frequently use their objects this isn't a big deal as dead objects get removed pretty quickly. There have been discussions adding some kind of return-hook or ahead of time recycling that would enable dead objects to be cleaned up sooner:

- #167
- #231

**Comment by zhuxiujia** [comment]
> That's to be expected. It's explained in the `README.md`:
> 
> > * **Deadpool is compatible with any executor.** Objects are returned to the pool using the Drop trait. The health of those objects is checked upon next retrieval and not when they are returned. Deadpool never performs any actions in the background. This is the reason why deadpool does not need to spawn futures and does not rely on a background thread or task of any type.
> 
> Whenever a object is dropped it is returned "as is" to the pool. Only upon the next `Pool::get` call is the health of the object checked. The pool itself never performs any background tasks.
> 
> For applications that frequently use their objects this isn't a big deal as dead objects get removed pretty quickly. There have been discussions adding some kind of return-hook or ahead of time recycling that would enable dead objects to be cleaned up sooner:
> 
> * [Ahead of time object creation/recycling #167](https://github.com/bikeshedder/deadpool/issues/167)
> * [Recycling smarter #231](https://github.com/bikeshedder/deadpool/discussions/231)


For connection pools used for databases, such as MySQL, the connection expires after 8 hours. If there are still connections in the pool that have not been deleted, they will remain in the requested state once they are used again

**Comment by bikeshedder** [comment]
I'm closing this issue in favor of the other issues mentioned. Feel free to reopen this or create a new issue if you think something is still missing.
