### ISSUE TITLE
deadpool-redis-cluster: remove redis_cluster_async dependency?

### ISSUE THREAD

**Issue by brocaar** [bikeshedder/deadpool#284]
Looking at the `redis_cluster_async` README (https://crates.io/crates/redis_cluster_async), it states:

> The functionality of this crate has been merged into the main [redis-rs](https://github.com/redis-rs/redis-rs) project.

So I think this dependency can be removed in favor of using this from the `redis` crate directly :-)

**Comment by bikeshedder** [comment]
I wonder if we should keep the `deadpool-redis` and `deadpool-redis-cluster` crates separate or deprecate the `-cluster` one and add those features to `deadpool-redis` instead?

**Comment by brocaar** [comment]
I think I would be in favor of a combined crate. In the end, it is targeting the same `redis` crate. This saves you probably as well the overhead of releasing this as separate crates.

Do you think it would make sense to add support for Redis Sentinel as well (https://docs.rs/redis/latest/redis/sentinel/index.html)?

**Comment by shoichi1023** [comment]
I agree with including redis-cluster support in the same package as deadpool-redis crate.
I also have high expectations for this work.

**Comment by bikeshedder** [comment]
This was fixed in #287 and I'm going to release a new version of `deadpool-redis` shortly.

**Comment by bikeshedder** [comment]
I just release `deadpool-redis 0.14.0` to crates.io: https://crates.io/crates/deadpool-redis/0.14.0
The `deadpool-redis-cluster 0.1.1` release is marked as deprecated: https://crates.io/crates/deadpool-redis-cluster/0.1.1
