### ISSUE TITLE
deadpool-postgres requires `cfg.dbname` even if `dbname` has already been given from `cfg.url`

### ISSUE THREAD

**Issue by beanpuppy** [bikeshedder/deadpool#290]
I've recently updated to `deadpool-postgres v0.12` to be able to use `cfg.url`. But there appears to be a logic error in these lines of [config.rs](https://github.com/bikeshedder/deadpool/blob/master/postgres/src/config.rs#L210-L216) where it doesn't check for `dbname` in the existing config that's created by the `url` field, meaning that it always errors with `ConfigError::DbnameEmpty`.

Setting `dbname` like before fixes it, but it overrides the value from `url` which is a bit annoying.

**Comment by bikeshedder** [comment]
I just released `deadpool-postgres 0.12.1` which fixes this issue:
- https://crates.io/crates/deadpool-postgres/0.12.1

Note to myself: *Write more unit tests!*
