### ISSUE TITLE
Official example for deadpool_postgres doesn't work?

### ISSUE THREAD

**Issue by erikschul** [bikeshedder/deadpool#296]
The official example at https://lib.rs/crates/deadpool-postgres
```
    let mut cfg = Config::new();
    cfg.dbname = Some("deadpool".to_string());
    cfg.manager = Some(ManagerConfig { recycling_method: RecyclingMethod::Fast });
    let pool = cfg.create_pool(Some(Runtime::Tokio1), NoTls).unwrap();
    for i in 1..10 {
        let mut client = pool.get().await.unwrap();
        let stmt = client.prepare_cached("SELECT 1 + $1").await.unwrap();
        let rows = client.query(&stmt, &[&i]).await.unwrap();
        let value: i32 = rows[0].get(0);
        assert_eq!(value, i + 1);
    }
```

gives this error:

`expected &(dyn ToSql + Sync), found &i32` for `client.query(&stmt, &[&i])`

**Comment by erikschul** [comment]
Solved by using `prepare_typed_cached`:

```
let stmt = client
            .prepare_typed_cached("SELECT 1 + $1", &[Type::INT4])
            .await
            .unwrap();
        let rows = client.query(&stmt, &[&i]).await.unwrap();
```

**Comment by erikschul** [comment]
Hmm, it builds correctly, perhaps this is a rust-analyzer bug:
<img width="888" alt="image" src="https://github.com/bikeshedder/deadpool/assets/128804597/d387e478-51af-4337-b489-c4b8b450d847">

**Comment by bikeshedder** [comment]
That's weird. `ToSql` is implemented for `&i32` via...
- https://docs.rs/tokio-postgres/latest/tokio_postgres/types/trait.ToSql.html#impl-ToSql-for-%26'a+T
- https://docs.rs/tokio-postgres/latest/tokio_postgres/types/trait.ToSql.html#impl-ToSql-for-i32

There should be no need to use `prepare_typed_cached` at all.

**Comment by erikschul** [comment]
Is there anything I can do to coerce/ignore for rust-analyzer?

**Comment by bikeshedder** [comment]
This seams to be a discrepancy between `rust-analyzer` and the rust compiler itself.

As I haven't specified the type in the `for`-loop it gets automatically deduced to a `i32`. At least that's what `rust-analyzer` is telling you. For whatever reason it does seam to use the generic `Integer` to check if `ToSql` is implemented.

You can make rust-analyzer happy by making `i` an actual `i32`:
```diff
  let mut cfg = Config::new();
  cfg.dbname = Some("deadpool".to_string());
  cfg.manager = Some(ManagerConfig { recycling_method: RecyclingMethod::Fast });
  let pool = cfg.create_pool(Some(Runtime::Tokio1), NoTls).unwrap();
- for i in 1..10 {
+ for i in 1..10i32 {
      let mut client = pool.get().await.unwrap();
      let stmt = client.prepare_cached("SELECT 1 + $1").await.unwrap();
      let rows = client.query(&stmt, &[&i]).await.unwrap();
      let value: i32 = rows[0].get(0);
      assert_eq!(value, i + 1);
  }
```

**Comment by bikeshedder** [comment]
I changed the READMEs accordingly. Thanks a lot!

**Comment by erikschul** [comment]
One temporary solution is to disable the diagnostic: `"rust-analyzer.diagnostics.disabled": ["E0308"]`
