### ISSUE TITLE
Is it a problem if `GenericClient` does not support dynamic dispatch?

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#298]
When removing the `async_trait` dependency this also rendered code using `&dyn GenericClient` unuseable. As alterantive `&impl GenericClient` can be used which avoids the dynamic dispatch.

I'm curious if anyone currently relies on `&dyn GenericClient` in the code and can't change it to `&impl GenericClient` instead.

**Comment by bikeshedder** [comment]
I'm pinging you because you mentioned the `GenericClient` in an Issue or PR in the past:

- @LouisGariepy
- @DmitryBochkarev
- @triptec
- @OskarPersson
- @dae
- @AdamJSoftware
- @kim

Could you check if this change affects you and if `deadpool-postgres` should still `async_trait` for the `GenericClient` rather than removing support for dynamic dispatch.

If you no longer user `deadpool-postgres` please accept my apologies for pinging you for no good reason.

**Comment by kim** [comment]
I haven’t used `deadpool-postgres`, but a custom `Manager` impl. It never needed to be a trait object, so I can wholeheartedly welcome this change 🙂

**Comment by dae** [comment]
I use deadpool-postgres indirectly now via diesel, but when I was using it directly I did not need dynamic dispatch.

**Comment by bikeshedder** [comment]
I plan to release a new version of deadpool end of month including this breaking change unless I hear anything else from deadpool users.

As far as I can tell the only point where the lack of dynamic dispatch could cause troubles is in `deadpool_postgres::GenericClient`. It is an easy fix though. Just replace `&dyn GenericClient` by`&impl GenericClient`. Performance wise this is beneficial as it avoids dynamic dispatch. The only downside I can think of is a slightly bigger binary size.
