### ISSUE TITLE
Code executes concurrently but not in parallel when awaiting tasks on .get()

### ISSUE THREAD

**Issue by bitemyapp** [bikeshedder/deadpool#31]
I've been eating around this particular cookie for awhile today.

When I rely solely on tasks calling `.get()`, even if I spawn 4 tasks, there's only ever one resource spawned by deadpool. This is pretty noticeable because the object pool I'm managing with `deadpool` is a pool of browsers created by `fantoccini`. You were in the thread earlier.

I'm believe that with `#[tokio::main(core_threads = 4, max_threads = 10)]` and:

```rust
tokio::spawn(async { scrape_worker(scraping1).await }),
```

for each worker, it should be working in parallel. To force it to create more resources I did this:

```rust
    let browser1 = scraping.client_pool.get().await;
    let browser2 = scraping.client_pool.get().await;
    let browser3 = scraping.client_pool.get().await;
    let browser4 = scraping.client_pool.get().await;
    let mut futures = vec![
        tokio::spawn(async { scrape_worker(scraping1).await }),
        tokio::spawn(async { scrape_worker(scraping2).await }),
        tokio::spawn(async { scrape_worker(scraping3).await }),
        tokio::spawn(async { scrape_worker(scraping4).await }),
    ];
    
    std::mem::drop(browser1);
    std::mem::drop(browser2);
    std::mem::drop(browser3);
    std::mem::drop(browser4);
    loop { };
```

It creates 4 browser windows, but the work proceeds in one browser window at a time. It does rotate in a consistent way between the 4 browser windows (counter-clockwise in my tiled wm), but they're still not parallel.

Here's the full code: https://gist.github.com/bitemyapp/f0ee741224f49be13104e5e3fc1af911

I doubt my hypothesis somewhat because the logs look like this:

```
[2020-01-17T02:15:08Z ERROR scraping_rs] Started scrape_page
[2020-01-17T02:15:08Z ERROR scraping_rs] Acquired client
[2020-01-17T02:15:08Z ERROR scraping_rs] Went to URL
[2020-01-17T02:15:09Z ERROR scraping_rs] Started scrape_page
[2020-01-17T02:15:09Z ERROR scraping_rs] Acquired client
[2020-01-17T02:15:09Z ERROR scraping_rs] Went to URL
```

If it were the case that they were concurrently blocking on `deadpool`'s `pool.get()` I should see consecutive `Started scrape_page`.

I feel like I must be missing something obvious here. If the code is getting spuriously linearized by something else, I'm guessing that would cause `deadpool` to only ever instantiate one resource right?

I did some profiling as well (for whatever call graph hierarchy attribution is worth with async) and I got something like this:

![image](https://user-images.githubusercontent.com/320177/72579154-cdae6200-389d-11ea-8205-1660ab09f8c1.png)

The purple/blue is the stuff that has the sub-string `deadpool`.

**Comment by bikeshedder** [comment]
I'm slightly confused by this code:

```rust
    let browser1 = scraping.client_pool.get().await;
    let browser2 = scraping.client_pool.get().await;
    let browser3 = scraping.client_pool.get().await;
    let browser4 = scraping.client_pool.get().await;
    let mut futures = vec![
        tokio::spawn(async { scrape_worker(scraping1).await }),
        tokio::spawn(async { scrape_worker(scraping2).await }),
        tokio::spawn(async { scrape_worker(scraping3).await }),
        tokio::spawn(async { scrape_worker(scraping4).await }),
    ];
    std::mem::drop(browser1);
    std::mem::drop(browser2);
    std::mem::drop(browser3);
    std::mem::drop(browser4);
```

This is seams wrong in two ways:

1. You never actually make use of the `browser1...4` handles
2. You should never use `std::mem::drop` on an `deadpool::managed::Object` as it will take the object from the pool without the pool getting a chance to reduce its size. The `managed` implementation currently does not provide an API to remove objects from the pool as I didn't see any use for it. It makes sense to add this feature though. (See #32)

Actually what the code does is create 4 client instances and `mem::drop` the handles. That's why you probably end up with 4 open browser windows which sit around and do nothing.

I just replaced the client code by a fake client and gave it a spin:

https://gist.github.com/bikeshedder/30bbcd5132616e845a5ccd3e4b60b4b8

```
[2020-01-17T09:16:20Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:20Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:20Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:20Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:20Z ERROR scraping_rs] Acquired client
[2020-01-17T09:16:20Z ERROR scraping_rs] Acquired client
[2020-01-17T09:16:20Z ERROR scraping_rs] Acquired client
[2020-01-17T09:16:20Z ERROR scraping_rs] Acquired client
[2020-01-17T09:16:21Z ERROR scraping_rs] Went to URL
[2020-01-17T09:16:21Z ERROR scraping_rs] Went to URL
[2020-01-17T09:16:21Z ERROR scraping_rs] Went to URL
[2020-01-17T09:16:21Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:21Z ERROR scraping_rs] Went to URL
[2020-01-17T09:16:21Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:21Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:21Z ERROR scraping_rs] Acquired client
[2020-01-17T09:16:21Z ERROR scraping_rs] Started scrape_page
[2020-01-17T09:16:21Z ERROR scraping_rs] Acquired client
[2020-01-17T09:16:21Z ERROR scraping_rs] Acquired client
```

Looks good to me.

**Comment by bitemyapp** [comment]
@bikeshedder >Actually what the code does is create 4 client instances and mem::drop the handles. That's why you probably end up with 4 open browser windows which sit around and do nothing.

Yes that's intentional. I was trying to see if I force the pool to create more than one client at the same time. When I remove that code there's just one browser instance getting passed between the different tasks.

Also, the `drop` releases the browsers back to the pool and they get used in the rotation. Just not in parallel:

![Screenshot from 2020-01-17 10-21-33](https://user-images.githubusercontent.com/320177/72628058-32f06a80-3913-11ea-9671-64f338549722.png)

Those browser windows would be blank. If I knew an easy way to record video on Linux/XMonad I would show you what it looks like but it rotates between each window, using a single browser at a time.

That code might seem spurious but it had a specific diagnostic purpose and functioned more or less as I intended.

Based on your diagnosis, I'm filing an issue with jonhoo's fantoccini to see if parallel/simultaneous operation isn't intended to work.

My current hypothesis is that without the weird browser instantiation hackery the code gets serialized by something else such that the pool never has more than one operative demand for a client. I'll close this for now. Thank you!

**Comment by bikeshedder** [comment]
Regarding `std::mem::drop`: I messed that one up. I have never used the explicit name `std::mem::drop`. I somehow thought you were using `std::mem::forget` which is a thing you should not do. `drop` is fine of course. I usually just call it `drop()` as it is globally available and no `use std::mem::drop` is required.

**Comment by bitemyapp** [comment]
This version makes simultaneous progress: https://gist.github.com/bitemyapp/f32e1ddac4cd2327dab8cee926eb7aec

I'm pretty sure at this point that `deadpool` is at least partly responsible and it explains the behavior of the code. I'm trying to find a screen recording app for Linux so I can show you before and after of my pooled and unpooled branches.

**Comment by bitemyapp** [comment]
Unpooled branch: https://youtu.be/fahLVUlpelQ
Pooled branch: https://youtu.be/s60MCOZn6tU

The pooled version has only two browsers but it becomes even more obvious with more of them spawned that it's round-robin'ing between the browser clients.

**Comment by bitemyapp** [comment]
Phew. It wasn't deadpool. It was my loop.

```diff
-    // while let Ok(url) = scraping.queue.pop() {
-    loop {
-        let maybe_url = scraping.queue.pop();
-        match maybe_url {
-            Err(err) => {
-                let five_seconds = Duration::new(5, 0);
-                tokio_timer::sleep(five_seconds);
-            },
-            Ok(url) => {
-              debug!("Starting scrape of url: {:?}", url);
-              {
-                  let been_scraped = scraping.scraped.get(&url);
-                  if been_scraped.is_some() {
-                      info!("URL already scraped, continuing: {:?}", url);
-                      continue;
-                  }
-              }
-                let _ = scrape_page(&mut scraping, url).await;
+    while let Ok(url) = scraping.queue.pop() {
+        debug!("Starting scrape of url: {:?}", url);
+        {
+            let been_scraped = scraping.scraped.get(&url);
+            if been_scraped.is_some() {
+                info!("URL already scraped, continuing: {:?}", url);
+                continue;
             }
         }
+        let _ = scrape_page(&mut scraping, url).await;
     }
-    // Ok(())
+    Ok(())
```

This diff reintroduces the bug/problem. the `while let ...` leads to 3 of the 4 spawned tasks dying at the beginning when there's only one base url in the queue. I need to change them to use a blocking work queue and have a separate kill signal or something. The grody raw loop I did to hack up the unpooled version fixed the problem. Sorry for the noise and thank you so much for the help!
