### ISSUE TITLE
Futures returned by methods on `deadpool_postgres::GenericClient` are not Send

### ISSUE THREAD

**Issue by and-reas-se** [bikeshedder/deadpool#320]
In 0.12.1 the futures returned by methods on `deadpool_postgres::GenericClient` were Send, but they are not in 0.13.1. I'm having trouble migrating to the new version due to this.

Is this an intentional breaking change or a bug?

**Comment by bikeshedder** [comment]
This is a bug and probably related to the removal of the `async_trait` crate.

I guess adding a `+ Send` to the GenericClient trait should do the trick. 🤔

**Comment by bikeshedder** [comment]
- #318

**Comment by bikeshedder** [comment]
I just released `deadpool-postgres` version `0.13.2` at crates.io which includes the fix ca9200453ddf7ce393863b7821c876f282b827b6:

- :package: https://crates.io/crates/deadpool-postgres/0.13.2
