### ISSUE TITLE
How to clear all items in unmanaged::Pool ?

### ISSUE THREAD

**Issue by xiaoxin-sky** [bikeshedder/deadpool#321]
I have a `type CkPoll = Arc<Mutex<unmanaged::Pool<CkModel>>>;`. Is there a way to clear all items from the pool, effectively reducing its size to zero?

**Comment by bikeshedder** [comment]
You can call the `close` method which does close the inner semaphores and clears the pool. All objects which are returned after that point get dropped and not added back to the pool.

This is mainly meant for shutdown purposes as all future calls to `get` and `get_timeout` will fail and objects currently outside of the pool will not be returned.

This **closes** the pool and there is currently no way to re-enable a closed pool.

If you just want to remove all objects currently being part of the pool you can do this:

```rs
while let Ok(_) = pool.try_remove() {}
```

This will only remove objects currently pooled. If you want to wait for objects to be returned so you can utilize the status like so:

```rs
while let pool.status().size > 0 {
    match pool.remove().await? {
        Err(PoolError::Closed) => break,
        _ => {},
    }
}
```

I haven't added a `clear` method to the public API as it isn't clear what it is supposed to do. Should it just remove the currently pooled objects or wait for all objects to be returned first?

If that really is a use-case I'm willing to add a `remove_all_pooled` method and maybe even a `remove_all` method that waits for the objects. Though I kind of doubt that anyone really needs this?

The implementation of those two methods would look almost identical to the code shown above.

**Comment by xiaoxin-sky** [comment]
Thank you for your answer.

I have cases like this:"I have an IP pool, where each entry includes IP information and the number of times it has been used. Once an IP retrieved from the pool reaches its usage limit, I delete that IP. At midnight every day, the IP pool is cleared."

I think "My Situation" should ask to delete all added items. Think of it like the following.
> This will only remove objects currently pooled. If you want to wait for objects to be returned so you can utilize the status like so:
> 
> ```rust
> while let pool.status().size > 0 {
>     match pool.remove().await? {
>         Err(PoolError::Closed) => break,
>         _ => {},
>     }
> }
> ```
> 

I'm currently using the following method to reset, not sure if there would be any issues with this method
![image](https://github.com/bikeshedder/deadpool/assets/42181585/9cf37161-ae11-4778-a786-87fe5d8669bc)

**Comment by bikeshedder** [comment]
If you were to use a managed pool you could use the `post_recycle` hook to take care of this:

```rs
const MAX_AGE: Duration = Duration::from_days(1);
const MAX_USES: usize = 1000;

builder.post_recycle(Hook::sync_fn(|obj, metrics| {
    if metrics.recycle_count > MAX_USES {
        Err(HookError::message("Max uses of object reached"))
    }
    if today() > object.creation_date() {
        Err(HookError::message("Object expired"))
    }
    Ok(())
}))
```

The unmanaged pool doesn't support this, yet.

Replacing the entire pool is the easiest and safest bet there is. Alternatively create a wrapper around the unmanaged pool that does exactly that:

```rs
#[derive(Clone)]
struct MyPool {
    pool: Pool<CkModel>,
}

impl MyPool {
    async fn get(&self) -> Result<Object<CkModel>, PoolError> {
        loop {
            let obj = self.pool.get().await?;
            if !obj.can_be_reused() {
                Object::take(obj);
                continue;
            }
            return obj;
        }
        None
    }
}
```

If you go for swapping the pool I'd recommend using `ArcSwap` instead as it doesn't require any locking unlike `Mutex`.

- :package: https://crates.io/crates/arc-swap

----

Side node: I'm still confused why you even use a pool/queue for that. Where do the IP addresses come from? How do they get added to the pool? If they are dynamic nature why did you opt for an unmanaged pool to begin with? A managed pool with a custom manager sounds like it could fit your use case a lot better.

**Comment by xiaoxin-sky** [comment]
Thank you very much for patiently explaining. I've now replaced `mutex` with `arc-swap`. It's worth noting that when using `arc-swap`, I encountered issues with concurrent requests. Here's the process for a single request: Upon receiving a request, I first check if there are available elements in the pool. If not, I add a new element to the pool.

The concurrency issue arises here. For example, let's assume the current pool status has a max_size of 2 and a size of 0. If 5 concurrent requests come in, all requests will see the pool status as `max_size = 2`, `size = 0`. Therefore, they will all attempt to add a new element to the pool. This means that using pool.add will result in only 2 requests being successfully responded to, while the other 3 requests will be blocked until an element is removed from the pool, because `max_size = 2`. Therefore, I've used `try_add` to address this concurrency issue. If anyone else encounters this problem, they might consider trying `try_add` . This is also why I initially used `mutex`, as `mutex` ensures that each request in concurrent requests gets the latest status.

Here is my sample code: (The "ip pool" is just an example. In the real scenario, I use "ck" (cookie) for timing.)
```rust
pub async fn get_ck_from_pool(&self) -> Result<Object<CkModel>, Box<dyn std::error::Error>> {
        let ck_pool = self.ck_pool.load();
        let ck_pool_status = ck_pool.status();
        if ck_pool_status.max_size > ck_pool_status.size && ck_pool_status.available == 0 {
            let new_ck_info = self.ck_service.enable_ck().await?;
          
            _ = ck_pool.try_add(new_ck_info);
        }

        let ck_info = ck_pool.get().await;
        if let Ok(ck_info) = ck_info {
            return Ok(ck_info);
        }

        Err("get ck error".into())
    }

```

Here is the complete type:

![image](https://github.com/bikeshedder/deadpool/assets/42181585/dfbcae16-8153-47f1-b825-a198fdbc2f51)



Once again, thank you for your patient responses and code examples, as well as providing me with some more flexible solutions. Especially, recommending the impressive library arc-swap has made my code run even more perfectly.

I will close this issue.

**Comment by bikeshedder** [comment]
All the pool status information is not guaranteed to be consistent. What do I mean by that. If you look at the code you can see the parts of the status loaded individually:

https://github.com/bikeshedder/deadpool/blob/c9fb037da6bfeef75dac5510db44ee669b22b70d/src/unmanaged/mod.rs#L336-L340

I could have sworn that I wrote about the status being [Eventual Consistent](https://en.wikipedia.org/wiki/Eventual_consistency). but I seam to have missed that. I just added the missing text:

https://github.com/bikeshedder/deadpool/blob/2a584a99fa6d80921f6428b7c5e7e6dc06b8e0a9/src/lib.rs#L34-L44

This doesn't cause any harm in your case as you still fall back to using `try_add` but you will be creating additional `CkModel` instances that never get added to the pool. Hence the need for `try_add`.

Looking at your code you've essentially built your own managed pool. May I recommend switching over to `deadpool::managed::Pool`? It results in much easier (and more correct) code according to your problem:

```rs
struct CkManager {
    service: CkService
}

impl managed::Manager for Manager {
    type Type = CkModel;
    type Error = CkError;

    async fn create(&self) -> Result<CkModel, CkError> {
        self.service.enable()
    }

    async fn recycle(
        &self,
        object: &mut CkModel,
        metrics: &managed::Metrics,
    ) -> managed::RecycleResult<CkError> {
        if metrics.recycle_count > MAX_USES {
            Err(RecycleError::StaticMessage("Max uses of object reached"))
        }
        if today() > object.creation_date() {
            Err(RecycleError::StaticMessage("Object expired"))
        }
        Ok(())
    }
}

#[tokio::main]
async fn main() {
    let manager = CkManager { ... };
    let pool = Pool::builder(manager).build().unwrap();
    ...
    // go crazy and call pool.get() now ... the managed pool takes care of everything for you. :-)
}
```

The code is obviously not complete as it includes placeholders such as `today()` and `object.creation_data()` that probably don't exist in your code. But it should give you a general idea.

Hope that helps! :+1:
