### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#322]
This issue tracks the progress of supporting WASM as a target.

- #316

**Comment by bikeshedder** [comment]
@shadaj Continuing our discussion from #316. I'm unsure if that's actually a case of rust-lang/cargo#1197.

If I'm not mistaken the conditional dependencies should work just fine with the latest Rust edition and resolver. :thinking:

Alternatively we could add a `rt-tokio-1-wasm` feature which does enable `deadpool/rt-tokio-1` but not the `runtime` feature of the `tokio-postgres` crate. That way we could still keep it a single feature to enable for most of the users and only add a special WASM feature flag for WASM users.

As features are additive it would be best if this was "fixed" in `tokio-postgres` where the `runtime` becomes a no-op if compiling for WASM.

@sfackler, what are your thoughts on that?

**Comment by bikeshedder** [comment]
@shadaj btw. would you be willing to share some of the code you use to create connection to PostgreSQL with WASM? Could that actually be added to a WASM specific runtime feature to `tokio-postgres` or `deadpool-postgres`? That would make using PostgreSQL on WASM a lot easier for future developers, no?

**Comment by bikeshedder** [comment]
I just released [:package: deadpool 0.12.1](https://crates.io/crates/deadpool/0.12.1) and [:package: deadpool-postgres 0.13.2](https://crates.io/crates/deadpool-postgres/0.13.2). I had to make a release due to #320 and including the current feature guards shouldn't break anything even though WASM support is currently broken according to @shadaj.

**Comment by shadaj** [comment]
Ahhhhh, we had forgotten to include `resolver = "2"` in a downstream crate we're building with `wasm-pack`. So sorry for the confusion, it all works now!

**Comment by bikeshedder** [comment]
Great. So this can be closed. The just released versions of the crates fix this. :partying_face:
