### ISSUE TITLE
deadpool-sqlite 0.8.1 release

### ISSUE THREAD

**Issue by danburkert** [bikeshedder/deadpool#324]
The most recent published version of `deadpool-sqlite` is 0.8.0, which depends on `deadpool` version `0.11`.  It looks like there is a `0.8.1` tag but that didn't get pushed to the crates repo.  Would it be possible to get that release pushed?

**Comment by bikeshedder** [comment]
Whopsies!

I just published `deadpool-sqlite 0.8.1` to crates.io:
- :package: https://crates.io/crates/deadpool-sqlite/0.8.1

Thank you! :rocket:
