### ISSUE TITLE
deadpool-sync::SyncWrapper is broken 

### ISSUE THREAD

**Issue by maan2003** [bikeshedder/deadpool#325]
https://github.com/bikeshedder/deadpool/blob/2a584a99fa6d80921f6428b7c5e7e6dc06b8e0a9/sync/src/lib.rs#L111-L122

Line 122 can panic because drop's task can get the lock first and make the value None

https://github.com/bikeshedder/deadpool/blob/2a584a99fa6d80921f6428b7c5e7e6dc06b8e0a9/sync/src/lib.rs#L155-L162

**Comment by bikeshedder** [comment]
The `InteractError::Aborted` is currently unused. I don't remember exactly why I added this variant to begin with.

It should be a great way to fix this issue in a way that doesn't result in a breaking change:

```diff
--- a/sync/src/lib.rs
+++ b/sync/src/lib.rs
@@ -119,13 +119,13 @@ where
         self.runtime
             .spawn_blocking(move || {
                 let mut guard = arc.lock().unwrap();
-                let conn = guard.as_mut().unwrap();
+                let conn: &mut T = guard.as_mut().ok_or(InteractError::Aborted)?;
                 #[cfg(feature = "tracing")]
                 let _span = span.enter();
-                f(conn)
+                Ok(f(conn))
             })
             .await
-            .map_err(|SpawnBlockingError::Panic(p)| InteractError::Panic(p))
+            .map_err(|SpawnBlockingError::Panic(p)| InteractError::Panic(p))?
     }
```

This is less invasive, doesn't change the API but should still resolve the issue, doesn't it? :thinking: 

Were you able to write a unit test that triggers the panic?
I'd really like to make sure this code stays panic free in the future.

**Comment by maan2003** [comment]
I think upstream code will just do on `interact().unwrap()`

example: 

https://github.com/matrix-org/matrix-rust-sdk/blob/5d549f17146907980bea8fe89a5664dc6365a73f/crates/matrix-sdk-sqlite/src/utils.rs#L118

> Were you able to write a unit test that triggers the panic?

No, this is very racy and hard to repro consistently.

**Comment by maan2003** [comment]
agreed

**Comment by bikeshedder** [comment]
I just release `deadpool-sync 0.1.4` including this patch:

- :adhesive_bandage: 2216358534b1d210ad81d6fc21f2357bdbe21b60
- :package: https://crates.io/crates/deadpool-sync/0.1.4

**Comment by maan2003** [comment]
BTW this error happen in 0.1.2 not in 0.1.3

**Comment by bikeshedder** [comment]
> BTW this error happen in 0.1.2 not in 0.1.3

Errr... that's even more weird as the only difference between those two versions is the inclusion of the LICENSE files. :clown_face: 

- https://github.com/bikeshedder/deadpool/pull/319

**Comment by maan2003** [comment]
I don't mean the issue didn't happen in 0.1.3, we just haven't used 0.1.3 in our client
