### ISSUE TITLE
Would you expect any issues when passing a reference to the pool into a handler?

### ISSUE THREAD

**Issue by GSGerritsen** [bikeshedder/deadpool#33]
I've got a weird performance issue going on and I just want to check if the way I'm doing this raises any flags.

There's basically a single handler in this Actix server, and depending on the type of request it dispatches to one of two functions. One of these functions needs a transaction, and it looks pretty much like this:

    async fn problem_fn(pool: &Pool) -> Result<stuff> {
        let mut client = pool.get().await.unwrap();
        let transaction = client.transaction().await.unwrap();
        let _result = transaction.execute(statement, params).await.unwrap();
        Ok(())
    }

The call chain is like: `registered_actix_handler -> dispatch_fn -> problem_fn`, where `dispatch_fn` has the `Pool` as part of its Actix `AppState`.

The other function just takes `(client: &Client)` as I've seen in most examples, and it doesn't seem to suffer from any issues, so I'm just wondering if passing the pool in as an argument to a handler might cause any issues with returning connections to the pool or something?

For some reason the handler that uses transactions takes a long time to process (especially when there are 0 connections in the pool when the server has just started). Subsequent requests run at an expected speed. When running on AWS EC2 instances, however, just about every request to this handler suffers from the long processing times, in case this adds any other clues.

I may be looking at the wrong problem here, but again I just want to check and see if I'm doing it wrong by passing in the pool itself like that. I have a feeling it has something to do with connections and not the SQL getting executed, because as I mentioned earlier there are times (usually after the first connection is made) that it processes quite quickly. Sorry for the super long issue and thanks in advance for any pointers.

**Comment by bikeshedder** [comment]
It does not matter wether you pass the pool as reference or clone it (it uses an `Arc` )  internally.

It might be caused by the `recycle` function taking some time. It is trivial in nature, but maybe the DB server or even network you are using does some strange stuff.

You could try setting some timeouts and see if `recycle` and/or `create` takes more time than expected.

**Comment by bikeshedder** [comment]
@GSGerritsen Did you find anything out about the cause of your problems?

**Comment by bikeshedder** [comment]
@GSGerritsen Feel free to reopen this Issue if you find that it's a `deadpool` issue.

If it's not an issue of `deadpool` I'd still like to know what is causing the issue for future references.
