### ISSUE TITLE
Disabling the config feature is not passed through from deadpool-lapin to deadpool

### ISSUE THREAD

**Issue by jbg** [bikeshedder/deadpool#34]
I have a bunch of projects that depend on one or both of `deadpool-lapin` and `deadpool-postgres` but don't depend on `deadpool` directly. In order to avoid the dependency on the `config` crate, which I don't need, I set `default-features = false` on `deadpool-lapin` and `deadpool-postgres`, but the removal of the feature is not passed through because default-features are enabled on `deadpool`.

Since people would not normally be depending on `deadpool` directly it might be better to have no default features on that crate, and have the implementation crates enable explicitly the features they need. Alternatively the shipped implementation crates could disable default features and only enable what they need.

**Comment by bikeshedder** [comment]
This is indeed an oversight by me. I want `deadpool` to have all features enabled by default, but `deadpool-*` should indeed depend on `deadpool` with `default-features = false`.

**Comment by bikeshedder** [comment]
I just released new versions including the fix on `crates.io`:

- https://crates.io/crates/deadpool/0.5.1
- https://crates.io/crates/deadpool-postgres/0.5.2
- https://crates.io/crates/deadpool-redis/0.5.1
