### ISSUE TITLE
Disabling prepared statements

### ISSUE THREAD

**Issue by TheOtherBrian1** [bikeshedder/deadpool#340]
Is it possible to prevent prepared statements from being generated? The [Supaviosr Pooler](https://github.com/supabase/supavisor) from [Supabase](https://supabase.com/) is not able to manage them in transaction mode.

**Comment by bikeshedder** [comment]
`deadpool-postgres` is merely a connection pool for `tokio-postgres` and adds a `StatementCache` on top.

`deadpool_postgres::Client` (aka `Object`) does implement `Deref<Target=tokio_postgres::Client>` and `DerefMut<Target=tokio_postgres::Client>` so you can call all the methods [`tokio_postgres::Client`](https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Client.html) provides.

You can use [`query_typed`](https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Client.html#method.query_typed) which does exactly what you want and is even documented for that very use case:

> Compared to `query`, this method allows performing queries without three round trips (for prepare, execute, and close) by requiring the caller to specify parameter values along with their Postgres type. Thus, this is suitable in environments where prepared statements aren’t supported (such as Cloudflare Workers with Hyperdrive).

Hope that helps! :+1:

**Comment by TheOtherBrian1** [comment]
@bikeshedder Thanks so much for the response. This is exactly what I was looking for

**Comment by bikeshedder** [comment]
Great! :+1:
