### ISSUE TITLE
unable to open database file via dsn path

### ISSUE THREAD

**Issue by thoongnv** [bikeshedder/deadpool#341]
I want to open the SQLite database file in read-only mode (to allow read access, e.g. SELECT) so I tried these DSN URLs:

```rust
let path = "sqlite:///data/mydb.sqlite?mode=ro";
// let path = "sqlite:/data/mydb.sqlite?mode=ro";
// let path = "sqlite:/data/mydb.sqlite";

let pool = deadpool_sqlite::Config::new(path).create_pool(deadpool_sqlite::Runtime::Tokio1).unwrap();
```

But none of this works, is there any wrong in config, or `deadpool-sqlite`/ `rusqlite` not support this?

**Comment by bikeshedder** [comment]
I think this is related to #214.
There is PR #292 which is a bit stale.

It should be fairly simple to complete this. I just haven't come around implementing it, yet.

PRs are always welcome! :+1:

**Comment by thoongnv** [comment]
oops, looks like it worked now with `file:` prefix

```rust
let path = "file:/data/mydb.sqlite?mode=ro";
```

**Comment by bikeshedder** [comment]
Thanks for the feedback! :+1:
