### ISSUE TITLE
Fix redis-cluster tests

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#344]
The redis-cluster test does fail in a random fashion:
- https://github.com/bikeshedder/deadpool/actions/runs/10249028862/job/28351551302
- https://github.com/bikeshedder/deadpool/actions/runs/10248994809/job/28351446716

It would be nice if anyone with better understanding of redis-cluster could look into that.

**Comment by bikeshedder** [comment]
@0xWOF Any idea what could be causing this? I'm pinging you as you're the one who originally wrote that unit test.

**Comment by 0xWOF** [comment]
I'll check it on weekend! I think difference between [redis_cluster_async](https://crates.io/crates/redis_cluster_async) and [redis-rs](https://crates.io/crates/redis) may cause of bug.

**Comment by rgrfoss** [comment]
https://github.com/bikeshedder/deadpool/pull/345#issue-2448936305
