### ISSUE TITLE
deadpool_diesel lost connection

### ISSUE THREAD

**Issue by jutbin** [bikeshedder/deadpool#346]
deadpool_diesel error after a while diesel error info:Lost connection to MySQL server during query

**Comment by bikeshedder** [comment]
The default [RecyclingMethod](https://docs.rs/deadpool-diesel/latest/deadpool_diesel/enum.RecyclingMethod.html) is [Fast](https://docs.rs/deadpool-diesel/latest/deadpool_diesel/enum.RecyclingMethod.html#variant.Fast) which doesn't perform any check of the underlying connection object. It's quite possible that the connection timed out and was closed while being pooled.

You can change this to [RecyclingMethod::Verified](https://docs.rs/deadpool-diesel/latest/deadpool_diesel/enum.RecyclingMethod.html#variant.Verified) which does perform a test query to ensure the connection is in working condition.

The [Manager::from_config](https://docs.rs/deadpool-diesel/latest/deadpool_diesel/struct.Manager.html#method.from_config) gives you the ability to pass in a [ManagerConfig](https://docs.rs/deadpool-diesel/latest/deadpool_diesel/struct.ManagerConfig.html).

Sadly diesel doesn't provide access to the underlying database object to check the connection. e.g. `deadpool-postgres` also supports multiple RecycleMethods but `Fast` does actually check [Client::is_closed()](https://docs.rs/tokio-postgres/0.7.10/x86_64-unknown-linux-gnu/tokio_postgres/client/struct.Client.html#method.is_closed) and doesn't usually run into this issue.

**Comment by jutbin** [comment]
You mean deadpool_diesel can't solve the problem of mysql connection disconnection, even if RecyclingMethod::Verified is used, then how can I use it in production environment?

**Comment by jutbin** [comment]
You mean deadpool_diesel can't solve the problem of mysql connection disconnection, even if RecyclingMethod::Verified is used, then how can I use it in production environment?

**Comment by jutbin** [comment]
You mean deadpool_diesel can't solve the problem of mysql connection disconnection, even if RecyclingMethod::Verified is used, then how can I use it in production environment?

**Comment by jutbin** [comment]
I found that using Verified sometimes takes a long time. How can I solve this problem? Is it caused by reconnecting to the MySQL pool? Isn't there a specified number of connections waiting to be connected in the connection pool at any time?

**Comment by bikeshedder** [comment]
That is to be expected if all pooled connections are dead.

Right now deadpool is only active when fetching objects from it. Let's assume you got N objects in the pool and all of them are dead. Deadpool will first try to recycle them all and then fall back to creating new ones.

I do plan on adding some kind of ahead of time object creation/recycling but that feature is still a bit on the drawing board as I want this kind of behavior to be opt in:

- #167

**Comment by bikeshedder** [comment]
Duplicate of #167
