### ISSUE TITLE
deadpool-redis does not export ProtocolVersion

### ISSUE THREAD

**Issue by bIgBV** [bikeshedder/deadpool#353]
I'm trying to create a pool of redis `ClusterClient` connections and want to use RESP3. Unfortunately, while `RedisConnectionInfo` is exported by the crate, the `ProtocolVersion` enum is not, and therefore I cannot construct a `deadpool_redis::ConnectionInfo` struct.:

```rust
let nodes = vec![
    ("redis://localhost", 7011),
    ("redis://localhost", 7021),
    ("redis://localhost", 7031),
];
let connectionInfo = nodes
    .into_iter()
    .map(|(url, port)| deadpool_redis::ConnectionInfo {
        addr: deadpool_redis::ConnectionAddr::Tcp(url.to_owned(), port),
        redis: deadpool_redis::RedisConnectionInfo {
            db: 0,
            protocol: deadpool_redis::config::ProtocolVersion::RESP3,
            username: None,
            password: None,
        },
    })
    .collect();
let config = Config {
    urls: None,
    connections: Some(connectionInfo),
    pool: None,
    read_from_replicas: false,
};
```

Is this intentional? If so, is there a different way to specify the protocol version? Because while the crate does export the `ClusterClientBuilder`, it doesn't look like as a user of the crate, I don't have the ability to provide an instantiated builder to the manager.

**Comment by bikeshedder** [comment]
Thanks a lot. That was indeed an oversight!

I just merged the PR made a release on crates.io:

- :package: https://crates.io/crates/deadpool-redis/0.17.1

**Comment by bIgBV** [comment]
Thank you for the quick response!
