### ISSUE TITLE
Question: Blocking issue when using deadpool-redis with a connection established over an SSH tunnel

### ISSUE THREAD

**Issue by honhimW** [bikeshedder/deadpool#361]
Hello,

I’m encountering an issue while using `deadpool-redis`🥹. When I directly connect to Redis, everything works as expected.
However, when I first create an SSH tunnel using `russh`, and then use deadpool-redis to connect to a local TcpListener.

```rust
let mut connection = pool.get().await?;
let pong: String = cmd("PING").query_async(&mut connection).await?;
assert!("PONG".eq_ignore_ascii_case(pong.as_str()));
// drop(connection); // drop manully can avoid the block problem
let mut connection = pool.get().await?; // will block here
```

[How i create a ssh tunnel](https://github.com/honhimW/ratisui/blob/13-connection-use-ssh-tunnel/src/ssh_tunnel.rs)

Repeated attempts to retrieve a connection from the pool result in blocking [Line:62](https://github.com/honhimW/ratisui/blob/c665a54f51f7918ec202ad278c8c6b4b98c47ecb/examples/ssh_tunnel.rs#L62). The only way to avoid this is to explicitly call `drop(con)` after retrieving the connection (let con = pool.get().await?), but this makes the code cumbersome to write. I’m not sure what could be causing this issue.

**Comment by bikeshedder** [comment]
From your code example I can only assume you're working with a pool size of 1?

Rust doesn't drop variables as early as possible. You can either `drop` that manually (like you've discovered already) or put this into a scope:
```rust
{
    let mut connection = pool.get().await?;
    let pong: String = cmd("PING").query_async(&mut connection).await?;
    assert!("PONG".eq_ignore_ascii_case(pong.as_str()));
    // connection leaves the scope and will be dropped after this line
}
{
    let mut connection = pool.get().await?;
    ...
}
```

If you need to access the `pong` variable outside of that scope you can use this programming pattern:

```rust
let pong: String = {
    let mut connection = pool.get().await?;
    cmd("PING").query_async(&mut connection).await? // no ";" at the end of this line
}; // this ";" is important as it is part of the let-statement
assert!("PONG".eq_ignore_ascii_case(pong.as_str()));
```

I do wonder why you need to write code like that? Why not reuse the connection you just got from the pool for the second query as well?

btw. if you want to get the connection from the pool, run a query and drop it immediately afterwards you can also use this pattern:

```rust
let pong: String = cmd("PING").query_async(&mut pool.get().await?).await?;
assert!("PONG".eq_ignore_ascii_case(pong.as_str()));
```

By not assigning the result of `pool.get().await?` to a variable it will be dropped right after the `query_async` function completes.

**Comment by honhimW** [comment]
Thanks for your reply~

> I do wonder why you need to write code like that? Why not reuse the connection you just got from the pool for the second query as well?

Actually, i won't use in this way. I'm just digging the root cause i met...
In another example, which is connect to the redis server directly with such code run perfectly in practice [Directly](https://github.com/honhimW/ratisui/blob/13-connection-use-ssh-tunnel/examples/redis_client.rs).

🤔On the other hand, i think is not about the rust scope problem. Because the problem also occurs in 
```rust
async fn initialize(&mut self) -> Result<()> {
    let mut connection = self.pool.get().await?;
    let value: Value = Cmd::new().arg("INFO").arg("SERVER").query_async(&mut connection).await?;
    // ...
    if redis_mode == "cluster" {
        self.initialize_cluster().await?;
    }
}

async fn initialize_cluster(&mut self) -> Result<()> {
    let mut connection = self.pool.get().await?; // block here
}
```

**Comment by bikeshedder** [comment]
In the new code you've shown the `connection` is not dropped when you call `initialize_cluster()` but at the end of `initialize()`.

Why do you even bother using a connection pool that way? If you need to run multiple queries I'd recommend either passing the `connection` object around or using a pool with a pool size > 1.

**Comment by honhimW** [comment]
Maybe the solution you offer can solve the problem.
But what I'm curious about is why the same code(default pool size == 1) works fine when I connect directly to the Redis server, but the issue only occurs when I connect to the address exposed by the TcpListener that is used to listen on the SSH tunnel.

**Comment by bikeshedder** [comment]
The default pool size is `4 * cpu_count`.

If you do create the pool with size 1 only one DB connection may exist at the same time. Therefore the `pool.get()` method will block until the only available connection is returned to the pool. If you don't drop the connection it's not returned to the pool and your code does block. It's perfectly normal and expected behavior.

If you don't use a pool you create multiple connections to Redis. It doesn't block because you're not limiting the connection count to 1.

**Comment by honhimW** [comment]
Oh~~
Sorry for the unverified statement earlier regarding the default pool size being 1.

I just discovered that, in fact, the pool size is 24 `status.max_size == 24` (on my machine), and even after `status.size == 1`, meaning only one connection was acquired, subsequent attempts to acquire a connection still result in a block.
Could it be that the issue is caused by an incorrect usage of the SSH tunnel, preventing the TcpListener from creating multiple connections?

**Comment by bikeshedder** [comment]
> Could it be that the issue is caused by an incorrect usage of the SSH tunnel, preventing the TcpListener from creating multiple connections?

Sure. That would also explain why the second connection hangs forever.

I just wonder as you stated that creating multiple connections without the pool works for you? `deadpool-redis` does nothing fancy here. It just connects to the redis host via the provided URL or ConnectionInfo.

**Comment by honhimW** [comment]
Alright.
I think I’m starting to get a clearer idea of how to solve the problem I’m facing. It's been very helpful from you!❤️❤️

**Comment by bikeshedder** [comment]
You're welcome! :+1:
