### ISSUE TITLE
Unable to switch to a different redis database when using deadpool-redis with sentinel

### ISSUE THREAD

**Issue by ederuiter** [bikeshedder/deadpool#367]
I tried to add support to chirpstack for redis sentinal (https://github.com/chirpstack/chirpstack/pull/553) 

However when I tried it with our redis configuration it fails with errors like:

```
Error occurred while creating a new object: Redis server refused to switch database - ResponseError: unknown command 'SELECT', with args beginning with: '1' : Redis server refused to switch database - ResponseError: unknown command 'SELECT', with args beginning with: '1' 
```

It seems that the sentinel client tries to select the database on the sentinel and not on the actual underlying redis connection.
Currently to configuration is pretty simple:

```rust
        let pool = deadpool_redis::sentinel::Config::from_urls(
            conf.redis.servers.clone(),
            conf.redis.master_name.clone(),
            deadpool_redis::sentinel::SentinelServerType::Master,
        )
        .builder()?
        .max_size(conf.redis.max_open_connections as usize)
        .build()?;
```

In this case the `conf.redis.servers` hold a single value with `redis://sentinel:26379/1`

Maybe there is another way of configuring the database for the redis connection; but this is how other clients like go-redis allow you to configure the database.

Is there any way to achieve this with the current version or is this a bug?

**Comment by bikeshedder** [comment]
As `deadpool-redis` only adds a pool (and serde compatible config structures) on top of the `redis` crate this is probably an issue of the underlying `redis` crate.

I think you should open an issue `redis-rs` repository: https://github.com/redis-rs/redis-rs

**Comment by ederuiter** [comment]
After some testing with `redis-rs` directly it seems this works:

```rust
use redis::{ Commands, RedisConnectionInfo };
use redis::sentinel::{ SentinelServerType, SentinelClient, SentinelNodeConnectionInfo };

fn main() {
    let nodes = vec!["redis://sentinel:26379"];
    let mut sentinel = SentinelClient::build(
        nodes,
        String::from("mymaster"),
        Some(SentinelNodeConnectionInfo {
            tls_mode: None,
            redis_connection_info: Some(RedisConnectionInfo {
                db: 1,
                username: None,
                password: None,
                protocol: Default::default(),
            }),
        }),
        redis::sentinel::SentinelServerType::Master,
    ).unwrap();

    let mut primary = sentinel.get_connection().unwrap();
    let count = primary.get("my_counter").unwrap_or("....".to_string());
    println!("Counter: {}", count);
}
```

The key here is to set the db separately in `redis_connection_info.db`.

How would I set the `redis_connection_info.db` from deadpool-redis?

**Comment by bikeshedder** [comment]
It should be the same with `deadpool-redis`: [deadpool_redis::RedisConnectionInfo](https://docs.rs/deadpool-redis/latest/deadpool_redis/struct.RedisConnectionInfo.html)

You can pass this as part of the [deadpool_redis::sentinel::Config](https://docs.rs/deadpool-redis/latest/deadpool_redis/sentinel/struct.Config.html) via the `connections` field.

**Comment by ederuiter** [comment]
Reading through the code it seems I would need to set the `sentinel_connection_info` field rather than the `connections` field of the Config struct (as the connections field only appear to be used to construct the list of sentinel servers; not the actual connection to the underlying redis servers).

However the `sentinel_connection_info` field is private and only seems to be initialized in the default case.

And also this field is only used to create a `SentinelNodeConnectionInfo`, so it only uses the `addr` field to set the tls_mode; this seems a bit backward as the `SentinelNodeConnectionInfo` will be used by the redis client to turn it into a `ConnectionInfo`; so I think the type of the `sentinel_connection_info` field should be a copy of the `SentinelNodeConnectionInfo` struct instead of the `ConnectionInfo` struct

**Comment by ederuiter** [comment]
I have tested this by adding a `with_sentinel_connection_info` method to the config struct:
```rust
/// Sets the connection info used to connect to the underlying redis servers (eg: db/username/..)
pub fn with_sentinel_connection_info(mut self, sentinel_connection_info: Option<ConnectionInfo>) -> Self {
    self.sentinel_connection_info = sentinel_connection_info;
    self
}
```

This works; although it feels a bit weird as you need to specify an address/port that is only used to determine the ssl mode (the actual address/port of the redis server comes from the sentinel).

```rust
     .with_sentinel_connection_info(Some(ConnectionInfo {
            addr: ConnectionAddr::Tcp("127.0.0.1".to_string(), 26379), //TODO: does not really matter; this is only used to determine ssl mode
            redis: RedisConnectionInfo {
                db: 1,
                username: None,
                password: None,
                protocol: Default::default(),
            }
        }))
```
@bikeshedder what do you think? Should I make a PR for this or do you have an other approach in mind?

Note: I do think the current name `sentinel_connection_info` is confusing, as it holds the configuration to connect to the underlying redis servers; not the sentinels (those are specified in the urls/connections fields)

**Comment by bikeshedder** [comment]
Ah, I see where the confusion is coming from. The `deadpool_redis::sentinel::Config` doesn't provide the `from_connection_info` method like the `deadpool_redis::Config` structure does. :facepalm:

I guess that's the missing method you were looking for?

Tbh. That entire config structure looks a bit weird. The way the SSL mode is determined is confusing at best.

Sorry for my ignorance. I don't run Redis Cluster or Redis Sentinel myself. I just merged the contributions for both cluster and sentinel after quickly reviewing them. As the contribution looked fine to me I didn't dive any deeper into the way cluster or sentinel configs need to be done.

All `deadpool-*` crates have config structures which are serde (de)serializable and support both the [config](https://crates.io/crates/config) and [figment](https://crates.io/crates/figment) crates. It'd be nice if this configuration could also be supported by a PR to fix the config structure of the sentinel config.

**Comment by ederuiter** [comment]
> Ah, I see where the confusion is coming from. The deadpool_redis::sentinel::Config doesn't provide the from_connection_info method like the deadpool_redis::Config structure does. 🤦
> 
> I guess that's the missing method you were looking for?

Almost; with a sentinel setup, it is a bit more complex. The idea of a sentinel setup is that you have multiple redis servers that are configured with replication and for each redis server you also run a sentinel; this checks the health of each redis server and when it finds that a server is unhealthy, it decided together with the other sentinels (by quorum) what to do: eg, if it was a master another server should be promoted to master and all clients should be redirected to the new master etc.

As for the client; they need to be aware of the sentinel setup and need to know which server is the current master etc etc. This is handled by the client; it connects to the first sentinel it can reach (which implements the same redis protocol) and asks what the current master(s)/replicas (dependent on the `SentinelServerType`)  are. After that it opens a separate connection to the underlying "real" redis server.

So in the configuration we need to be able to specify 2 different connections:

1) The connection to the sentinels; currently defined by the `urls` and/or the `connections` fields. (note: this connection cannot use any other database than 0 as the SELECT command is not implemented in the sentinel)

2) The connection to the underlying real redis servers; currently defined by the private `sentinel_connection_info` field. The host/port are not used as they are obtained from the sentinel server.

So what is missing is the configuration for the second type; this is currently only possible via the private field `sentinel_connection_info` and is a bit awkward

Ideally the type of the `sentinel_connection_info` field (or what we should rename this field to) should mirror the `SentinelNodeConnectionInfo` type in the redis-rs crate .. the comments also hint to that; but also mention that it does not implement `debug`:

```rust
    // SentinelNodeConnectionInfo doesn't implement debug, so we can't
    // use it as a field, also they have identical fields.
    sentinel_connection_info: Option<ConnectionInfo>,
```

Here is where my rust knowledge currently ends; I can make some changes to existing code and test things; but the whole traits/structs are still a bit magical to me :-) 
So if you have any advise how this should be structured, I will happily try it and test it; but otherwise I am a bit lost here.

**Comment by bikeshedder** [comment]
Looking at the code I think two changes need to be made:
1. Remove the `sentinel_connection_info` from the config struct. It's only used internally and cloned/modified at various places in a confusing way.
2. Add a `pub tls_mode: Option<TlsMode>` instead.

We could also make the `sentinel_connection_info` public but if I'm not mistaken it's really just the wrong type. It contains a lot of fields completely irrelevant for the sentinel config, no?

**Comment by ederuiter** [comment]
https://github.com/bikeshedder/deadpool/pull/369 

^ this implements a third option renaming the `sentinel_connection_info` to `sentinel_node_connection_info` and changing the type to `Option<SentinelNodeConnectionInfo>` 

This mirrors the way you configure the sentinel client in redis-rs (see https://github.com/bikeshedder/deadpool/issues/367#issuecomment-2483801778 for an example)

It involves mirroring another struct from redis-rs (SentinelNodeConnectionInfo) but I think this makes it the most flexible and clear.

**Comment by bikeshedder** [comment]
It's fine for me. Even though the `redis_rs` API looks kinda silly to me I can see the charm of keeping it in sync with `redis-rs`.
