### ISSUE TITLE
How do I run a query without statement caching?

### ISSUE THREAD

**Issue by amokfa** [bikeshedder/deadpool#376]
Our service uses both static and dynamic queries (generated using a query builder). We do not want the dynamic queries to be cached for obvious reasons? How do we execute a query without caching it?

**Comment by bikeshedder** [comment]
The statement cache is only used when using the [prepare_cached](https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.ClientWrapper.html#method.prepare_cached) or [prepare_typed_cached](https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.ClientWrapper.html#method.prepare_typed_cached) methods.

For your dynamic queries you would want to use the methods without the `_cached` suffix and for the static ones you would want to use the ones with the `_cached` suffix.

If you have any suggestions how to explain this better in the docs please let me know and/or create a PR for that.

**Comment by amokfa** [comment]
I went through this old discussion #75 and this is my understanding:
* For static queries, do `conn.execute(conn.prepare_cached(query_string))`. Library will take care of caching.
* For dynamic queries, do `conn.execute(query_string)`. 
Is this correct?

**Comment by bikeshedder** [comment]
Yes. That's correct. :+1:

**Comment by amokfa** [comment]
Understood, thanks. Regarding the documentation, the docstring for `Client::prepare_cached` just says `Like Client::prepare_cached`.  Maybe it's referring to tokio_postgres client but I couldn't find a way of navigating to it.

**Comment by bikeshedder** [comment]
The docstring states:

> Like [tokio_postgres::Client::prepare()](https://docs.rs/tokio-postgres/0.7.12/x86_64-unknown-linux-gnu/tokio_postgres/client/struct.Client.html#method.prepare), but uses an existing [Statement](https://docs.rs/tokio-postgres/0.7.12/x86_64-unknown-linux-gnu/tokio_postgres/statement/struct.Statement.html) from the [StatementCache](https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.StatementCache.html) if possible.

![image](https://github.com/user-attachments/assets/1dadbe54-f9eb-466b-8b6b-7f2ad03d6f5b)

Where did you find the docstring that doesn't mention the statement cache?

**Comment by amokfa** [comment]
![image](https://github.com/user-attachments/assets/12c4c5e3-4a42-4e70-964e-993c8d87ad37)
![image](https://github.com/user-attachments/assets/cbf9f8d1-33cb-4206-a974-f2440fefa6ec)

I see the descriptive docstring that you shared on `Transaction::prepare_cached`

**Comment by bikeshedder** [comment]
Ah, I see. Yes, that's the docstring of the `GenericClient`. It does indeed reference `prepare_cached` of the `deadpool_postgres::Client` which in turn contains the explanation of the statement cache. :see_no_evil:
