### ISSUE TITLE
Add timeout function to unmanaged pool implementation or additional documentation

### ISSUE THREAD

**Issue by nihiluis** [bikeshedder/deadpool#41]
I think it would be an intuitive addition to add a timeout wrapper to the unmanaged Pool. A new method (like the managed one) would perhaps be preferrable instead of returning a Result for the normal get()? If you don't deem such a method necessary, I'd suggest to add a snippet to the documentation for noobs like me who are not very familiar with tokio. 

Based on this: https://github.com/bikeshedder/deadpool/issues/9

See your comment
> Unmanaged pools don't recycle and create new objects. Thus only wait_timeout makes any sense. Right now this can already be achieved by calling tokio::time::timeout(std::time::Duration::from_secs(5), pool.get()). It might make sense to add this as a configuration option to the pool nonetheless. It will require the pool.get() method to return a Result<T, PoolError> instead of T.

I like the lib. Thank you.

**Comment by bikeshedder** [comment]
In order to make it API similar to the managed version of the pool I think the following new and/or changed structs and methods are needed:

```rust
use std::time::Duration;

pub struct PoolConfig {
    timeout: Option<Duration>
}

pub enum PoolError {
    Timeout
}

impl Pool {
    ...
    pub fn from_config(&self, config: PoolConfig) -> Self { ... }
    pub async fn timeout_get(&self, duration: Option<Duration>) -> Result<Object<T>, PoolError> { ... }
    pub async fn get(&self) -> Result<Object<T>, PoolError> { ... }
}
```

That `Result<_, PoolError>` seams a bit overkill for now. `Option<_>` would do just fine. I'm however thinking of adding a `close/terminate/shutdown` method which can be used to mark a pool as unuseable so that all future `get` calls return an error immediately. See #42

**Comment by bikeshedder** [comment]
Now that #42 has finally been implemented the `get` methods of the unmanaged pool return a `Result<T, PoolError>` and `PoolError::Timeout` exists. Thus adding this feature just seams natural.

I want to land this feature together with #68.
