### ISSUE TITLE
How to test if initialization is successful?

### ISSUE THREAD

**Issue by devisions** [bikeshedder/deadpool#44]
Hi everyone!

Just a quick question: how can we test if the database pool gets initialized successfully? <br>
The context is quite simple: imagine the `.env` file containing a typo for the password option (either in the name such as `PASS` instead of `PASSWORD` or just the value as in this example):
```env
PG.USER=myuser
PG.PASSWORD=wrongpass
PG.HOST=127.0.0.1
PG.PORT=5432
PG.DBNAME=mydb
```
Currently, a code such as the one below does not detect/receive any issue at startup:\
```rust
let pool = match config.pg.create_pool(NoTls) {
        Ok(pool) => pool,
        Err(err) => {
            println!(">>> Database connection error: '{}'", err);
            exit(1);
        }
    };
```

Of course, the issue appears when the `Client` is used:
```
Error getting db connection: Backend(Error { kind: Connect, cause: Some(Os { code: 2, kind: NotFound, message: "No such file or directory" }) })
```

Any advice, please?
Thanks

**Comment by bikeshedder** [comment]
This is the expected behaviour. The pool creation should never fail for reasons other than an invalid configuration. This is explained in the [`README`](https://github.com/bikeshedder/deadpool/blob/master/README.md) of the `deadpool` crate:

> - **Identical startup and runtime behaviour.** When writing long running application there usually should be no difference between startup and runtime if a database connection is temporarily not available. Nobody would expect an application to crash if the database becomes unavailable at runtime. So it should not crash on startup either. Creating the pool never fails and errors are only ever returned when calling `Pool::get()`.
> 
>   If you really want your application to crash on startup if objects can not be created on startup simply call `pool.get().await.expect("DB connection failed")` right after creating the pool.

I guess I need to make this a lot clearer in the documentation of the crate.

You are not the first one to ask for something like that and I'm thinking about adding a `initial_size` configuration option which will cause an error if not at least `initial_size` objects can be created during pool creation.

**Comment by devisions** [comment]
Hi Michael,

You're absolutely right. Appreciate your elaborated answer.

I got initially confused by the fact that VSCode's code completion did not show any `get()` method.
So, I generally tend to use IDEA more that I would want (I really love VSCode, but the intellisense for Rust needs more work).

Related to the documentation, maybe an explicit reference to `deadpool`'s features would help. I was just looking into `deadpool_postgres`.

Once again, thanks for the feedback and for the nice creates!
