### ISSUE TITLE
README comparison is out of date

### ISSUE THREAD

**Issue by djc** [bikeshedder/deadpool#46]
> bb8 uses a callback based interface (See pool.run) and provides the same configuration options as r2d2. At the time of writing there is no official release which supports async/.await.

This is no longer true. There is now a guard-based interface and an official release which supports async/await.

**Comment by bikeshedder** [comment]
Thanks. Hope the new text is fine for you: c33145cb06566756a3a59d2dcb3a609fd0a00d73

**Comment by djc** [comment]
Looks fine for me, thanks!
