### ISSUE TITLE
deadpool-posgtres: support LISTEN/NOTIFY

### ISSUE THREAD

**Issue by NAlexPear** [bikeshedder/deadpool#48]
## Feature request:

The current way that `tokio_postgres` supports async messaging in Postgres is through the [`poll_message`](https://docs.rs/tokio-postgres/0.5.3/tokio_postgres/struct.Connection.html#method.poll_message) method on a `Connection` (from which you can construct your own stream with `stream::poll_fn`). Unfortunately, `deadpool-postgres` only exposes `Client`s without access to those `Client`s' counterpart `Connection`. It would be great if `deadpool-postgres` could support this use-case directly in some way.

## Propsed changes:

There's probably a few ways this could be done, but the ones that I thought of:

1. Allow underlying connections to to be extracted from the `ClientWrapper` through a method. 
2. implement `Into<Connection>` for `ClientWrapper`
3. if exposing the underlying `Connection` isn't the right approach, then `ClientWrapper` could expose a stream of `tokio_postgres::AsyncMessage`s directly through a method

Of course, if there's another workaround, please let me know! And if any of these approaches :point_up: sound appropriate, then I'd be happy to take a crack at implementing this myself.

**Comment by bikeshedder** [comment]
I think there is currently no way to get acces to the `Connection` object once it was spawned to a reactor. This is not really a `deadpool-postgres` issue but lies in the design of how connections are spawned. This is straight from the docs of `tokio-postgres`:

```rust
let (client, connection) =
    tokio_postgres::connect("host=localhost user=postgres", NoTls).await?;
tokio::spawn(async move {
    if let Err(e) = connection.await {
        eprintln!("connection error: {}", e);
    }
});
```

Once the connection is spawned there is no turning back. That connection is gone and you don't have any access to it.

---

Why do you even want to use a pool anyways? That pool is primarily meant for short lived workers which perform just a few queries and drop the client afterwards. The pool picks those up and makes them available for future workers which don't need to connect to the DB but can use an already connected client. In case of publish/subscribe you're probably never going to drop that client, are you?

**Comment by bikeshedder** [comment]
@NAlexPear I'm closing this for now as I don't see how this is supposed to work and like to clean up the issue backlog a bit. Feel free to reopen this issue if you have an idea how to implement this feature.
