### ISSUE TITLE
Missing support for rust-postgres TransactionBuilder

### ISSUE THREAD

**Issue by Dowwie** [bikeshedder/deadpool#50]
This is a request to enhance deadpool_postgres to support [rust-postgres::TransactionBuilder](https://docs.rs/postgres/0.17.2/postgres/struct.TransactionBuilder.html), which works like so:

https://docs.rs/postgres/0.17.2/postgres/struct.Client.html#method.build_transaction

```rust
let mut transaction = client.build_transaction()
    .isolation_level(IsolationLevel::RepeatableRead)
    .start()?;
```

**Comment by bikeshedder** [comment]
I just released `deadpool-postgres` 0.5.6 which includes this feature. Sorry for the long delay:

- https://github.com/bikeshedder/deadpool/blob/master/postgres/CHANGELOG.md
- https://crates.io/crates/deadpool-postgres/0.5.6
