### ISSUE TITLE
get a problem when use pipe()

### ISSUE THREAD

**Issue by somewheve** [bikeshedder/deadpool#51]
```
use deadpool_redis::pipe;
let mut data: Vec<String> = pipe().cmd("lrange").arg("ck_cache".to_string()).arg(0).arg(-1).query_async(&mut connection).await.unwrap();
```
I want to get the data from the ck_cache. but no data return 

when I just use cmd()  and return data.  
I don't know why. and I hope to execute lrange and ltrim, so I choose the pipe() function. 

the whole command is 

```
let mut data: Vec<String> = pipe().cmd("lrange").arg("ck_cache".to_string()).arg(0).arg(-1).cmd("ltrim").arg("ck_cache").arg(length).arg(-1).ignore()
                        .query_async(&mut connection).await.unwrap();
```
it will delete data successfully but no data

**Comment by bikeshedder** [comment]
Does it work when using `redis` without `deadpool-redis`? Do you have a test case that could be added to `deadpool-redis`? That would make reproduction of this a lot easier.

**Comment by somewheve** [comment]
I will give a example two days later .  sorry to reply too later

**Comment by bikeshedder** [comment]
Any news on this. Did you figure it out or is this a deadpool issue that needs to be fixed?

**Comment by bikeshedder** [comment]
I didn't hear back from you so I assume this issue isn't `deadpool` related. Marking this issue as `invalid` and closing it for now.

Feel free to reopen this issue if this is not the case.
