### ISSUE TITLE
how to use #[tokio::test]

### ISSUE THREAD

**Issue by IThawk** [bikeshedder/deadpool#54]
```
error: the async keyword is missing from the function declaration
  --> hawk_data\src\db\redis.rs:44:7
   |
44 | async fn test_managed_basic() {
   |       ^^
```
when I use  #[tokio::test] , how to solve this error?

**Comment by bikeshedder** [comment]
`#[tokio::test]` should expect an async function and the code you pasted does indeed contain the `async` keyword. Is this the only compliler error you are getting?

This should compile fine and not report any errors:

```rust
#[tokio::test]
async fn test_foo() {
    assert!(true);
}
```

Actually this sounds more like a [tokio](https://github.com/tokio-rs/tokio/) issue to me. I would recommend asking on the Discord server: https://discord.gg/tokio

Does this only happen when trying to use `deadpool` or is this problem actually unrealated?

**Comment by bikeshedder** [comment]
Closing this as `invalid`. Haven't received any updates for over a week now and I don't think this is a `deadpool` issue.
