### ISSUE TITLE
Enable the use of High Level Commands

### ISSUE THREAD

**Issue by chmoder** [bikeshedder/deadpool#55]
There appears to be a more idiomatic/readable way to interact with redis called [High Level Commands](https://docs.rs/redis/0.16.0/redis/#executing-high-level-commands).  Is it difficult to add this feature?

**Comment by bikeshedder** [comment]
`deadpool_redis::Connection` is just an alias for `deadpool::Object<ConnectionWrapper, RedisError>` which is a wrapper for `ConnectionWrapper` which is an wrapper for the `redis::aio::Connection`. Both wrappers implement `Deref` and `DerefMut`. Thus you can use them exactly like a `redis::aio::Connection`. In order for the High-Level Commands to be available to you all you need is to `use redis::AsyncCommands`.

The example on the website is for the sync version which uses `redis::Commands`. Later on that page the `AsyncCommands` is mentioned, too: https://docs.rs/redis/0.16.0/redis/#async

I just added an example to the tests (aea1edb6c4904badaa916965d6917a29a57c7395):

```rust
#[tokio::main]
#[test]
async fn test_high_level_commands() {
    use redis::AsyncCommands;
    let pool = create_pool();
    let mut conn = pool.get().await.unwrap();
    let _: () = conn.set("deadpool/hlc_test_key", 42).await.unwrap();
    let value: isize = conn.get("deadpool/hlc_test_key").await.unwrap();
    assert_eq!(value, 42);
}
```

Hope that helps. :+1:

**Comment by chmoder** [comment]
I'm guessing `use redis::AsyncCommands` is what I forgot to do.

Thank you for the example, I will use it later today.  Thank you for making this cargo package!

**Comment by chmoder** [comment]
I tried to get this example working in my project unsucessfully.  I have two questions, and [here](https://github.com/chmoder/rust-practice-actix-web/tree/feat-high-level-commands) is a branch that implements the above design but doesn't compile yet.

1) Is there a way to access redis from deadpools namespace?
error[E0432]: unresolved import `redis`
 --> src/main.rs:3:5
  |
3 | use redis::AsyncCommands;
  |     ^^^^^ use of undeclared type or module `redis`

2) This is the error I get when I try to use a high level function.
error[E0599]: no method named `get` found for struct `deadpool::managed::Object<deadpool_redis::ConnectionWrapper, redis::types::RedisError>` in the current scope
   --> src/main.rs:7:17
    |
7   |     return conn.get(key).await.unwrap();
    |                 ^^^ method not found in `deadpool::managed::Object<deadpool_redis::ConnectionWrapper, redis::types::RedisError>`

**Comment by bikeshedder** [comment]
You need to add the `redis` crate to your `cargo.toml` in order for `use redis::AsyncCommands` to work.

I could reexport the `redis` crate or juest the `AsyncCommand` trait from `deadpool_redis`, but I'm unsure if that's really a good idea: https://www.reddit.com/r/rust/comments/4jvxaz/reexport_dependency_pros_and_cons/

**Comment by chmoder** [comment]
Question (1) I was able to get around, I too was not sure if it is a good idea to reexport it in `deadpool_redis`.  Question (2) is the one that I have not been able to get around, and is the reason I opened this issue originally.

Here is an example of using deadpool_redis in actix.  It works **AMAZING** with redis `CMD`.  But I can't get the high level commands to work because  the compiler thinks `conn.get` is trying to be accessed on a `deadpool::managed::Object<deadpool_redis::ConnectionWrapper, redis::types::RedisError>`.

https://github.com/chmoder/rust-practice-actix-web/blob/feat-high-level-commands/src/main.rs

Thank you for the help!

**Comment by chmoder** [comment]
🤦 I pushed close and comment.

**Comment by bikeshedder** [comment]
Actually `conn.get` should just work. You can get a better error message when you write it like that: `(**conn).get(...)`

Maybe it really is caused by incompatible crate versions and reexporting `redis` from `deadpool_redis` is a good idea after all...

**Comment by chmoder** [comment]
Thank you for suggesting that; I thought I was crazy yesterday.

This is the error I could not get past:
```python
    let mut conn = redis_pool.get().await.unwrap();
    let _:() = (**conn).set(key, val).await.unwrap();
```

error[E0599]: no method named `get` found for struct `redis::aio::Connection` in the current scope
   --> src/main.rs:7:21
    |
7   |     return (**conn).get(key).await.unwrap();
    |                     ^^^ method not found in `redis::aio::Connection`
    | 
   ::: /Users/tcross/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.15.1/src/aio.rs:106:1
    |
106 | pub struct Connection {
    | ---------------------
    | |
    | doesn't satisfy `_: redis::commands::AsyncCommands`
    | doesn't satisfy `redis::aio::Connection: redis::aio::ConnectionLike`
    | 
   ::: /Users/tcross/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.15.1/src/commands.rs:198:8
    |
198 |     fn get<K: ToRedisArgs>(key: K) {
    |        ---
    |        |
    |        the method is available for `std::boxed::Box<redis::aio::Connection>` here
    |        the method is available for `std::sync::Arc<redis::aio::Connection>` here
    |        the method is available for `std::rc::Rc<redis::aio::Connection>` here
    |
    = note: the method `get` exists but the following trait bounds were not satisfied:
            `redis::aio::Connection: redis::aio::ConnectionLike`
            which is required by `redis::aio::Connection: redis::commands::AsyncCommands`
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use redis::commands::AsyncCommands;
    |

**Comment by bikeshedder** [comment]
```
    | doesn't satisfy `_: redis::commands::AsyncCommands`
```

That sounds like you're using redis crates of different versions.
If this is indeed the case I'll release a new `deadpool_redis` version which reexports the used redis version.

Could you please check if this is really the case by using the exact same redis version as `deadpool_redis` uses: `0.15.1`

It would be great if there wasn't this kind of dependency. It seams though I have to make a new `deadpool_redis` release every time the `redis` crate is updated. That's a bummer. :disappointed:

**Comment by chmoder** [comment]
You got it!  I tested with `0.15.1` as well and it compiles now.  That is a bummer, especially when the types or interface doesn't change (it seems).

**Comment by bikeshedder** [comment]
I do now see why `tokio_postgres` has those feature flags which include the version numbers of the crates it depends on. I'm looking for alternatives to reexporting `redis` but if this is the only viable option I'll do it. I really dislike this kind of release coupling.

**Comment by chmoder** [comment]
No rush, I am using this library to learn Rust - so no customers are waiting for this on my end.  I did test 2 other pools, and yours *by far* is the most efficient.  Excellent work on `deadpool_redis`.

**Comment by bikeshedder** [comment]
I will reexport `redis` and also release a new release of `deadpool-redis` soon.

**Comment by bikeshedder** [comment]
I just release `deadpool-redis` 0.6.0 which has an updated redis version and also reexports the `redis` crate so you don't need to "guess" the compatible versions:

- https://github.com/bikeshedder/deadpool/blob/master/redis/CHANGELOG.md
- https://crates.io/crates/deadpool-redis/0.6.0

**Comment by chmoder** [comment]
Thank you, this is excellent! 

https://github.com/chmoder/rust-practice-actix-web/commit/7f769a653dd1cb6cd831635daa6536153f3f5976

![Excellent!](https://thumbs.gfycat.com/PersonalZanyFalcon-size_restricted.gif)
