### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by anton-dutov** [bikeshedder/deadpool#6]
Please add any ci, for example travis - login on travis-ci.org via github, enable ci for this project, and add `.travis.yml` to project root

    language: rust
    rust:
    - stable

    sudo: false

    cache: cargo

    script:
    - cargo build --verbose
    - cargo test --verbose

**Comment by bikeshedder** [comment]
Done! :+1:

I did not expect that setting up Travis CI is so simple. I will keep Travis CI on my toolbelt for future F/OSS projects. :slightly_smiling_face:
