### ISSUE TITLE
Re-export deadpool PoolConfig from deadpool-redis (et co)

### ISSUE THREAD

**Issue by gyfis** [bikeshedder/deadpool#73]
I'm probably missing something obvious, but I don't seem to be able to construct a PoolConfig struct manually, like this:

```rust
let config = Config { url: Some(redis_uri()), pool: PoolConfig { max_size: 32 } };
```

I think this would work if the `deadpool-redis` re-exported the PoolConfig from `deadpool`. Would you be open to this addition? 

Thanks!

**Comment by bikeshedder** [comment]
That makes a lot of sense. :+1:

What do you think of #74 ?
