### ISSUE TITLE
Caching prepared statements

### ISSUE THREAD

**Issue by Kerndog73** [bikeshedder/deadpool#75]
I'm using deadpool-postgres and realised that I'm not using prepared statements efficiently. In each of my request handlers, I grab a connection from the pool, create a prepared statement, execute the statement, and finally discard the statement. While I'm gaining the security benefits of prepared statements, I'm not getting the performance benefits. Prepared statements depend on the connection but I get a different connection from the pool each time so caching isn't so simple.

I'm not too sure how to do this as this is all unfamiliar territory for me. Perhaps I need to keep a struct with the connection and statements in the pool rather than just the connection? I guess I'd need to discard deadpool-postgres in that case and use the core library...?

Any advice on how to proceed?

**Comment by bikeshedder** [comment]
`deadpool-postgres` has a builtin statement cache:
> This crate implements a deadpool manager for tokio-postgres and also provides a statement cache by wrapping tokio_postgres::Client and tokio_postgres::Transaction.

For the implementation have a look at https://github.com/bikeshedder/deadpool/blob/6583aa742d8baf109de2d98bbee5a648c83340e5/postgres/src/lib.rs#L272 and https://github.com/bikeshedder/deadpool/blob/6583aa742d8baf109de2d98bbee5a648c83340e5/postgres/src/lib.rs#L346

You are right that you might be getting a different `ClientWrapper` object on subsequent calls to `pool.get`, but if you're doing this many times and execute the same query over and over again you will end up with a pool that is full of `ClientWrapper` objects that have this statement cached.

Are you trying to implement your own statement cache on top of `deadpool-postgres`? If that's what you're trying to do you need to implement your own `Manager` and `ClientWrapper`.

**Comment by bikeshedder** [comment]
You must not hold a reference to the `PreparedStatement` object between `pool.get` calls. Simply drop it and call `prepare` again. The `StatementCache` will take care of grabbing the `PreparedStatement` object that is prepared for the current `Client`.

**Comment by Kerndog73** [comment]
Oh that's awesome. It's all handled for me. Thanks for your help!
