### ISSUE TITLE
redis: set username and password

### ISSUE THREAD

**Issue by MarcoIeni** [bikeshedder/deadpool#79]
Since version 6, redis added authentication with username and password. See docs [here](https://redis.io/commands/auth).
With the `redis` crate It is possible to set those with the [redis::ConnectionInfo](https://docs.rs/redis/0.19.0/redis/struct.ConnectionInfo.html#structfield.username) struct, but deadpool_redis doesn't expose a way to set them I think.

**Comment by bikeshedder** [comment]
I will add support for the `redis::ConnectionInfo` struct in the next release. In the mean time you can provide the `username` and `passwd` as part of the URL: https://docs.rs/redis/0.19.0/src/redis/connection.rs.html#202

**Comment by bikeshedder** [comment]
This should work: `redis://user:password@127.0.0.1:6379/0`
Port and database number are optional of course: `redis://user:password@127.0.0.1`

**Comment by MarcoIeni** [comment]
Thank you very much, I didn't know that! :D

**Comment by bikeshedder** [comment]
I just added #80 to track the support of `redis::ConnectionInfo`.
