### ISSUE TITLE
Create a pool with max_size and timeouts

### ISSUE THREAD

**Issue by vkandy** [bikeshedder/deadpool#83]
Hello,
I am trying to create a pool using `Pool::from_config` method. The reason is I want to be able to use `Timeouts`. However, `deadpool::managed::config::PoolConfig` is private. How can I create a pool with timeouts?

```
        let mgr = Manager::from_config(pg_config, NoTls, mgr_config);
        // deadpool::managed::config::PoolConfig is private
        let pool_config = deadpool::managed::config::PoolConfig {
            max_size: config.pool_max_size,
            timeouts: deadpool::managed::Timeouts {
                create: Some(Duration::from_secs(1)),
                wait: Some(Duration::from_secs(5)),
                recycle: Some(Duration::from_secs(5)),
            },
        };
        let pool = Pool::from_config(mgr, pool_config);
```
Thanks!

**Comment by bikeshedder** [comment]
The `config` module is private, but the `PoolConfig` object is not and is reexported from `deadpool::managed`:

```rust
use deadpool::managed::PoolConfig;
```

Where did you come up with the name `deadpool::managed::config::PoolConfig`? Did I mention this somewhere in the docs or did you come up with this based on the source code?

**Comment by vkandy** [comment]
OK, thank you! Yes, I was trying to use timeouts so I was browsing the code. It wasn't clear to me how to get a connection with timeout. I was attempting calls with `try_get` and `timeout_get` which are `pub` but I couldn't instantiate `Timeouts`.

This can be closed.
