### ISSUE TITLE
deadpool-postgres includes a second default host even when the "host" Config param is specified

### ISSUE THREAD

**Issue by nickfrostatx** [bikeshedder/deadpool#84]
See https://docs.rs/deadpool-postgres/0.7.0/src/deadpool_postgres/config.rs.html#328-345

If you specify the `host` parameter but not `hosts`, dedpool-redis tacks on a second host. On Unix, this will be `/tmp` if you aren't running a postgres server locally. As a workaround, you can instead use the `hosts` parameter instead with a single host.

This has the frustrating effect of hiding any errors from connecting to the actual remote host. If tokio-postgres fails to connect to the first host, it will move on and try the second one. Instead of your actual error, you'll get something like `error connecting to server: No such file or directory (os error 2)`. I think that's what was behind the error message in https://github.com/bikeshedder/deadpool/issues/82.

**Repro**
```rust
let mut cfg = deadpool_postgres::Config::new();
cfg.dbname = Some("mydb".into());
cfg.host = Some("my-remote-host.com".into());
println!("{:?}", cfg.get_pg_config().unwrap());
```

```
Config { ... host: [Tcp("my-remote-host.com"), Unix("/tmp")], ...}
```

**Comment by bikeshedder** [comment]
While looking at this I also found another issue that's related to this: #87
