### ISSUE TITLE
Add support for `Pool::get` with timeout

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/deadpool#9]
I currently wonder if it should be part of the core of deadpool:

Adding a timeout to the `Pool::get` function should be as simple as wrapping the call in one of the following two:

- https://docs.rs/tokio/0.2.2/tokio/time/fn.timeout.html
- https://docs.rs/async-std/1.2.0/async_std/future/fn.timeout.html

There is little to be gained when using `Pool::get_timeout()` over `timeout(Pool::get())`, is there?

**Comment by bikeshedder** [comment]
I currently wonder wether I should add a `get_timeout` function which allows specifying multiple timeouts:
```rust
async fn get_timeout(&self,
    create_timeout: Option(Duration),
    wait_timeout: Option(Duration),
    recycle_timeout: Option(Duration))
```

- `create_timeout` is the maximum time spent when creating a new connection
- `wait_timeout` is the maximum time spent when waiting for a connection to become available in the pool.
- `recycle_timeout` is the maximum time spent recycling an existing connection

For most applications I guess `wait_timeout` and an overall timeout would suffice so I wonder if `create_timeout` and `recycle_timeout` is even needed.

**Comment by nihiluis** [comment]
I think this feature was only added to managed pools?

I think this would be beneficial for unmanaged ones too. Or do you not think so? If so, why?

**Comment by bikeshedder** [comment]
Unmanaged pools don't recycle and create new objects. Thus only `wait_timeout` makes any sense. Right now this can already be achieved by calling `tokio::time::timeout(std::time::Duration::from_secs(5), pool.get())`. It might make sense to add this as a configuration option to the pool nonetheless. It will require the `pool.get()` method to return a `Result<T, PoolError>` instead of `T`.

Feel free to open a new issue so we can discuss this.

**Comment by ansjsun** [comment]
my lib not use tokio . use async-st,   when add this config 
it has err:
````
thread 'main' panicked at 'there is no timer running, must be called from the context of Tokio runtime', /Users/sunjian11/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/time/driver/handle.rs:24:9
````

@bikeshedder

**Comment by bikeshedder** [comment]
That's a bummer. I thought `tokio::time::timeout` was runtime agnostic. It seams that this is not the case.

Could you please open a new issue regarding this issue? I don't use `async-std` myself at the moment that's why I didn't notice that.
