### ISSUE TITLE
fails to connect to database when TLS is enabled

### ISSUE THREAD

**Issue by mbuscemi** [bikeshedder/deadpool#91]
I have a web app. I have developed out some basic features. I have put it into a live environment, once on Heroku and later on DigitalOcean. In live, the connection to the Postgres database needs to use TLS. In all permutations of code I have tried, the server starts correctly, but any attempt to load a page results in this error: `thread 'actix-rt:worker:2' panicked at 'could not create db client from pool: Backend(Error { kind: Tls, cause: Some(Custom { kind: InvalidData, error: WebPKIError(UnknownIssuer) }) })'`.

I have tried loading in the PEM file from AWS servers (in the case of Heroku, which uses AWS Postgres instances), adding webpki roots, rustls native certs, even forcing an authorizer that validates everything. Same error.

You can find a minimal version of the code that reproduces this error [here](https://github.com/mbuscemi/actix-unknown-issuer-minimal/tree/main). The error occurs at `src/main.rs:33:47` (reproduced on Heroku).

Env variables in that app are:

- server_addr=0.0.0.0
- pg.*=(from my database instance)
- use_ssl=true
- use_rustls_root_store=false
- add_webpki_roots=false
- use_custom_cert_resolver=false

I can turn any of the last three variables (which control various portions of the TLS setup) on or off and it makes no difference. Same error message. The same with the optional db_ca_cert, which can be set with the name of the pem file or not set. It makes no difference.

**Comment by bikeshedder** [comment]
Did you figure it out?

**Comment by bikeshedder** [comment]
I believe this is not a problem of `deadpool-postgres`. Please check if you get the same errors when connecting with `tokio-postgres` without `deadpool`. Feel free to reopen this issue if you can connect with `tokio-postgres` but not `deadpool-postgres`.

Since I haven't heard back from you for the past 2 weeks I'm closing this issue for the time being.
