### ISSUE TITLE
Incorrect Pool Status counts

### ISSUE THREAD

**Issue by pjenvey** [bikeshedder/deadpool#92]
We're seeing managed Pool's `Status::available` count exceed its `max_size` (https://github.com/mozilla-services/syncstorage-rs/issues/803).

In `Pool::timeout_get`: `available`'s only decremented once at the beginning of the method but its loop potentially evicts > 1 idle connection.

1. Consider the case of `Manager::recycle` evicting "stale" connections from the Pool by returning `PoolError` and the loop encountering multiple errors. Idle connections are pop'd from the pool for every error, `available` (and `size`) should decrement for each. 
2. Errors propagated from `apply_timeout()...await?` might also cause incorrect stats.

**Comment by pjenvey** [comment]
#93 is a potential fix for 1.

**Comment by bikeshedder** [comment]
Whops. I referenced the wrong issue with my commit. This is fixed in 15f94710a7e653941924379ae66fb2371a6946ee
